import test from 'node:test'
import assert from 'node:assert/strict'
import fs from 'node:fs'
const sql=fs.readFileSync(new URL('../supabase/migrations/20260808000100_platform_phase5_complete.sql',import.meta.url),'utf8')
const repairGroup2Sql=fs.readFileSync(new URL('../supabase/migrations/20260808000200_repair_group_2_studio_persistence_integrity.sql',import.meta.url),'utf8')
const atomicCreateSql=fs.readFileSync(new URL('../supabase/migrations/20260808000300_repair_group_2_atomic_layout_creation.sql',import.meta.url),'utf8')
const repairGroup2Migrations=[sql,repairGroup2Sql]
test('migration defines atomic release activation and one-active invariant',()=>{assert.match(sql,/create or replace function public\.activate_release/i);assert.match(sql,/one_active_site_release/i);assert.match(sql,/where status = 'active'/i)})
test('migration protects published layouts and content',()=>{assert.match(sql,/Published layout versions are immutable/);assert.match(sql,/Pages in published layout versions are immutable/);assert.match(sql,/Published content revisions are immutable/)})
test('Studio document persistence is atomic and rejects cross-version page ownership',()=>{for(const migration of repairGroup2Migrations){assert.match(migration,/create or replace function public\.save_layout_document/i);assert.match(migration,/Page % belongs to another layout version/i);assert.match(migration,/where id = target_version_id and layout_id = target_layout_id\s+for update/i)}})
test('page immutability is privileged, serialized and rejects every version reassignment',()=>{for(const migration of repairGroup2Migrations){assert.match(migration,/create or replace function public\.protect_published_layout_page\(\)[\s\S]*?security definer[\s\S]*?set search_path = pg_catalog, pg_temp/i);assert.match(migration,/old_version_status/i);assert.match(migration,/new_version_status/i);assert.match(migration,/select status into old_version_status[\s\S]*for update/i);assert.match(migration,/select status into new_version_status[\s\S]*for update/i);assert.match(migration,/new\.layout_version_id is distinct from old\.layout_version_id/i);assert.match(migration,/set revision_token = gen_random_uuid\(\)/i)}})
test('layout publication requires the exact validated draft revision',()=>{for(const migration of repairGroup2Migrations){assert.match(migration,/revision_token uuid not null default gen_random_uuid\(\)/i);assert.match(migration,/drop function if exists public\.publish_layout_version\(uuid, text, text\)/i);assert.match(migration,/expected_revision_token uuid/i);assert.match(migration,/published\.revision_token is distinct from expected_revision_token/i);assert.match(migration,/where id = target_version_id and status = 'draft' and revision_token = expected_revision_token/i);assert.match(migration,/Draft changed after validation\. Revalidate before publishing/i)}})
test('Repair Group 2 forward migration is narrow and service-role-only',()=>{const functions=[...repairGroup2Sql.matchAll(/create or replace function public\.(\w+)/gi)].map(match=>match[1]).sort();assert.deepEqual(functions,['protect_published_layout_page','protect_published_layout_version','publish_layout_version','save_layout_document']);assert.equal((repairGroup2Sql.match(/\balter table\b/gi)||[]).length,1);assert.match(repairGroup2Sql,/alter table public\.layout_versions add column if not exists revision_token uuid not null default gen_random_uuid\(\)/i);assert.doesNotMatch(repairGroup2Sql,/\b(?:create|drop)\s+table\b/i);assert.doesNotMatch(repairGroup2Sql,/\b(?:create|drop)\s+policy\b/i);assert.doesNotMatch(repairGroup2Sql,/\bsite_releases\b|\bactivate_release\b|\bstorage\.objects\b/i);assert.match(repairGroup2Sql,/revoke all on function public\.protect_published_layout_page\(\) from public, anon, authenticated/i);assert.match(repairGroup2Sql,/revoke all on function public\.save_layout_document[\s\S]*from public, anon, authenticated/i);assert.match(repairGroup2Sql,/grant execute on function public\.save_layout_document[\s\S]*to service_role/i);assert.match(repairGroup2Sql,/revoke all on function public\.publish_layout_version\(uuid, uuid, text, text\) from public, anon, authenticated/i);assert.match(repairGroup2Sql,/grant execute on function public\.publish_layout_version\(uuid, uuid, text, text\) to service_role/i)})
test('initial layout creation atomically inserts the layout, draft and starter pages',()=>{assert.match(atomicCreateSql,/create or replace function public\.create_layout_document/i);assert.match(atomicCreateSql,/insert into public\.layouts/i);assert.match(atomicCreateSql,/insert into public\.layout_versions/i);assert.match(atomicCreateSql,/insert into public\.layout_pages/i);assert.match(atomicCreateSql,/status, design_tokens, created_by[\s\S]*'draft'/i);assert.doesNotMatch(atomicCreateSql,/delete from public\.layouts/i);assert.match(atomicCreateSql,/grant execute on function public\.create_layout_document[\s\S]*to service_role/i)})
test('atomic layout creation retries only slug conflicts with deterministic suffixes',()=>{assert.match(atomicCreateSql,/exception when unique_violation/i);assert.match(atomicCreateSql,/violated_constraint <> 'layouts_slug_key'/i);assert.match(atomicCreateSql,/slug_suffix := slug_suffix \+ 1/i);assert.match(atomicCreateSql,/candidate_slug := normalized_slug \|\| '-' \|\| slug_suffix::text/i);assert.doesNotMatch(atomicCreateSql,/\bsite_releases\b|\bactivate_release\b|\bstorage\.objects\b/i)})
test('atomic layout slug normalization lowercases before filtering',()=>{assert.match(atomicCreateSql,/normalized_slug := btrim\(regexp_replace\(lower\(coalesce\(layout_slug_base_value, ''\)\), '\[\^a-z0-9\]\+', '-', 'g'\), '-'\)/i);assert.equal('My Layout'.toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-+|-+$/g,''),'my-layout')})
test('normal profile updates cannot self-promote role',()=>{assert.match(sql,/profiles_admin_update/);assert.match(sql,/role = 'admin'/)})

test('release snapshots include media references',()=>{assert.match(sql,/media_snapshot jsonb/i)})
test('draft deletes return OLD instead of silently cancelling',()=>{assert.match(sql,/if tg_op = 'DELETE' then return old; end if;/i)})

test('settings revisions and activated release snapshots are immutable',()=>{assert.match(sql,/Published settings revisions are immutable/);assert.match(sql,/Activated release snapshots are immutable/)})
