import test from 'node:test'
import assert from 'node:assert/strict'
import fs from 'node:fs'
const sql=fs.readFileSync(new URL('../supabase/migrations/20260808000100_platform_phase5_complete.sql',import.meta.url),'utf8')
const repairGroup2Sql=fs.readFileSync(new URL('../supabase/migrations/20260808000200_repair_group_2_studio_persistence_integrity.sql',import.meta.url),'utf8')
const atomicCreateSql=fs.readFileSync(new URL('../supabase/migrations/20260808000300_repair_group_2_atomic_layout_creation.sql',import.meta.url),'utf8')
const repairGroup3Sql=fs.readFileSync(new URL('../supabase/migrations/20260808000400_repair_group_3_release_integrity.sql',import.meta.url),'utf8')
const layoutLifecycleSql=fs.readFileSync(new URL('../supabase/migrations/20260808000500_studio_layout_lifecycle.sql',import.meta.url),'utf8')
const repairGroup2Migrations=[sql,repairGroup2Sql]
test('migration defines atomic release activation and one-active invariant',()=>{assert.match(sql,/create or replace function public\.activate_release/i);assert.match(sql,/one_active_site_release/i);assert.match(sql,/where status = 'active'/i)})
test('migration protects published layouts and content',()=>{assert.match(sql,/Published layout versions are immutable/);assert.match(sql,/Pages in published layout versions are immutable/);assert.match(sql,/Published content revisions are immutable/)})
test('Studio document persistence is atomic and rejects cross-version page ownership',()=>{for(const migration of repairGroup2Migrations){assert.match(migration,/create or replace function public\.save_layout_document/i);assert.match(migration,/Page % belongs to another layout version/i);assert.match(migration,/where id = target_version_id and layout_id = target_layout_id\s+for update/i)}})
test('page immutability is privileged, serialized and rejects every version reassignment',()=>{for(const migration of repairGroup2Migrations){assert.match(migration,/create or replace function public\.protect_published_layout_page\(\)[\s\S]*?security definer[\s\S]*?set search_path = pg_catalog, pg_temp/i);assert.match(migration,/old_version_status/i);assert.match(migration,/new_version_status/i);assert.match(migration,/select status into old_version_status[\s\S]*for update/i);assert.match(migration,/select status into new_version_status[\s\S]*for update/i);assert.match(migration,/new\.layout_version_id is distinct from old\.layout_version_id/i);assert.match(migration,/set revision_token = gen_random_uuid\(\)/i)}})
test('layout publication requires the exact validated draft revision',()=>{for(const migration of repairGroup2Migrations){assert.match(migration,/revision_token uuid not null default gen_random_uuid\(\)/i);assert.match(migration,/drop function if exists public\.publish_layout_version\(uuid, text, text\)/i);assert.match(migration,/expected_revision_token uuid/i);assert.match(migration,/published\.revision_token is distinct from expected_revision_token/i);assert.match(migration,/where id = target_version_id and status = 'draft' and revision_token = expected_revision_token/i);assert.match(migration,/Draft changed after validation\. Revalidate before publishing/i)}})
test('Repair Group 2 forward migration is narrow and service-role-only',()=>{const functions=[...repairGroup2Sql.matchAll(/create or replace function public\.(\w+)/gi)].map(match=>match[1]).sort();assert.deepEqual(functions,['protect_published_layout_page','protect_published_layout_version','publish_layout_version','save_layout_document']);assert.equal((repairGroup2Sql.match(/\balter table\b/gi)||[]).length,1);assert.match(repairGroup2Sql,/alter table public\.layout_versions add column if not exists revision_token uuid not null default gen_random_uuid\(\)/i);assert.doesNotMatch(repairGroup2Sql,/\b(?:create|drop)\s+table\b/i);assert.doesNotMatch(repairGroup2Sql,/\b(?:create|drop)\s+policy\b/i);assert.doesNotMatch(repairGroup2Sql,/\bsite_releases\b|\bactivate_release\b|\bstorage\.objects\b/i);assert.match(repairGroup2Sql,/revoke all on function public\.protect_published_layout_page\(\) from public, anon, authenticated/i);assert.match(repairGroup2Sql,/revoke all on function public\.save_layout_document[\s\S]*from public, anon, authenticated/i);assert.match(repairGroup2Sql,/grant execute on function public\.save_layout_document[\s\S]*to service_role/i);assert.match(repairGroup2Sql,/revoke all on function public\.publish_layout_version\(uuid, uuid, text, text\) from public, anon, authenticated/i);assert.match(repairGroup2Sql,/grant execute on function public\.publish_layout_version\(uuid, uuid, text, text\) to service_role/i)})
test('initial layout creation atomically inserts the layout, draft and starter pages',()=>{assert.match(atomicCreateSql,/create or replace function public\.create_layout_document/i);assert.match(atomicCreateSql,/insert into public\.layouts/i);assert.match(atomicCreateSql,/insert into public\.layout_versions/i);assert.match(atomicCreateSql,/insert into public\.layout_pages/i);assert.match(atomicCreateSql,/status, design_tokens, created_by[\s\S]*'draft'/i);assert.doesNotMatch(atomicCreateSql,/delete from public\.layouts/i);assert.match(atomicCreateSql,/grant execute on function public\.create_layout_document[\s\S]*to service_role/i)})
test('atomic layout creation retries only slug conflicts with deterministic suffixes',()=>{assert.match(atomicCreateSql,/exception when unique_violation/i);assert.match(atomicCreateSql,/violated_constraint <> 'layouts_slug_key'/i);assert.match(atomicCreateSql,/slug_suffix := slug_suffix \+ 1/i);assert.match(atomicCreateSql,/candidate_slug := normalized_slug \|\| '-' \|\| slug_suffix::text/i);assert.doesNotMatch(atomicCreateSql,/\bsite_releases\b|\bactivate_release\b|\bstorage\.objects\b/i)})
test('atomic layout slug normalization lowercases before filtering',()=>{assert.match(atomicCreateSql,/normalized_slug := btrim\(regexp_replace\(lower\(coalesce\(layout_slug_base_value, ''\)\), '\[\^a-z0-9\]\+', '-', 'g'\), '-'\)/i);assert.equal('My Layout'.toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-+|-+$/g,''),'my-layout')})
test('normal profile updates cannot self-promote role',()=>{assert.match(sql,/profiles_admin_update/);assert.match(sql,/role = 'admin'/)})

test('release snapshots include media references',()=>{assert.match(sql,/media_snapshot jsonb/i)})
test('draft deletes return OLD instead of silently cancelling',()=>{assert.match(sql,/if tg_op = 'DELETE' then return old; end if;/i)})

test('settings revisions and activated release snapshots are immutable',()=>{assert.match(sql,/Published settings revisions are immutable/);assert.match(sql,/Activated release snapshots are immutable/)})

test('Repair Group 3 allocates release numbers with a database sequence',()=>{assert.match(repairGroup3Sql,/create sequence if not exists public\.site_release_number_seq/i);assert.match(repairGroup3Sql,/alter column release_number set default nextval\('public\.site_release_number_seq'/i);assert.match(repairGroup3Sql,/select coalesce\(max\(release_number\), 0\)/i);assert.match(repairGroup3Sql,/revoke all on sequence public\.site_release_number_seq from public, anon, authenticated/i)})

test('Repair Group 3 ties validation to an exact release snapshot',()=>{assert.match(repairGroup3Sql,/snapshot_revision_token uuid not null default gen_random_uuid\(\)/i);assert.match(repairGroup3Sql,/release_validation_results[\s\S]*snapshot_revision_token uuid/i);assert.match(repairGroup3Sql,/target\.snapshot_revision_token is distinct from expected_snapshot_revision_token/i);assert.match(repairGroup3Sql,/Release changed during validation\. Revalidate the current snapshot/i);assert.match(repairGroup3Sql,/snapshot_revision_token = target\.snapshot_revision_token/i)})

test('Repair Group 3 upgrades the reused per-check validation table without discarding history',()=>{assert.match(repairGroup3Sql,/add column if not exists valid boolean not null default false/i);assert.match(repairGroup3Sql,/add column if not exists issues jsonb not null default '\[\]'::jsonb/i);assert.match(repairGroup3Sql,/column_name = 'passed'/i);assert.match(repairGroup3Sql,/set valid = coalesce\(passed, false\)/i);assert.match(repairGroup3Sql,/alter column check_name drop not null/i);assert.match(repairGroup3Sql,/alter column passed drop not null/i);assert.doesNotMatch(repairGroup3Sql,/drop column (check_name|passed|message|details)/i)})

test('Repair Group 3 enforces legal release transitions and ready immutability',()=>{assert.match(repairGroup3Sql,/Ready and activated release snapshots are immutable/i);assert.match(repairGroup3Sql,/new\.id is distinct from old\.id/i);assert.match(repairGroup3Sql,/transition_name = 'validation' and old\.status = 'draft' and new\.status = 'ready'/i);assert.match(repairGroup3Sql,/old\.status = 'ready' and new\.status = 'active'/i);assert.match(repairGroup3Sql,/old\.status = 'active' and new\.status = 'superseded'/i);assert.match(repairGroup3Sql,/transition_name = 'rollback'[\s\S]*old\.status = 'superseded' and new\.status = 'active'/i);assert.match(repairGroup3Sql,/Illegal release transition from % to %/i);assert.match(repairGroup3Sql,/Site releases are append-only and cannot be deleted/i)})

test('Repair Group 3 activation is serialized, validated and atomic',()=>{assert.match(repairGroup3Sql,/create or replace function public\.activate_release\([\s\S]*expected_snapshot_revision_token uuid[\s\S]*actor_user_id uuid/i);assert.match(repairGroup3Sql,/pg_advisory_xact_lock/i);assert.match(repairGroup3Sql,/target\.status <> 'ready'/i);assert.match(repairGroup3Sql,/perform public\.assert_release_inputs\(target_release_id\)/i);assert.match(repairGroup3Sql,/release_validation_results[\s\S]*validation_kind = 'candidate'[\s\S]*valid = true/i);assert.match(repairGroup3Sql,/set_config\('app\.release_transition', 'activation', true\)/i);assert.match(repairGroup3Sql,/create unique index if not exists one_active_site_release/i)})

test('Repair Group 3 rollback is a distinct controlled operation',()=>{assert.match(repairGroup3Sql,/create or replace function public\.rollback_release/i);assert.match(repairGroup3Sql,/target\.status <> 'superseded'/i);assert.match(repairGroup3Sql,/Rollback requires a different active release/i);assert.match(repairGroup3Sql,/validation_kind[\s\S]*'rollback'/i);assert.match(repairGroup3Sql,/set_config\('app\.release_transition', 'rollback', true\)/i);assert.match(repairGroup3Sql,/'release_rolled_back'/i)})

test('Repair Group 3 release mutations are service-role-only',()=>{for(const signature of ['create_site_release\\(uuid, uuid, uuid, jsonb, jsonb, text, uuid\\)','record_release_validation\\(uuid, uuid, boolean, jsonb, text, uuid\\)','activate_release\\(uuid, uuid, uuid\\)','rollback_release\\(uuid, uuid, jsonb, text, uuid\\)']){assert.match(repairGroup3Sql,new RegExp(`revoke all on function public\\.${signature} from public, anon, authenticated`,'i'));assert.match(repairGroup3Sql,new RegExp(`grant execute on function public\\.${signature} to service_role`,'i'))}assert.match(repairGroup3Sql,/drop policy if exists site_releases_admin_all/i);assert.match(repairGroup3Sql,/create policy site_releases_admin_read/i);assert.match(repairGroup3Sql,/revoke insert, update, delete on public\.site_releases from anon, authenticated/i);assert.match(repairGroup3Sql,/revoke insert, update, delete on public\.release_validation_results from anon, authenticated/i)})

test('Repair Group 3 commits release audit events with transitions',()=>{assert.match(repairGroup3Sql,/Audit logs are append-only/i);assert.match(repairGroup3Sql,/create trigger protect_audit_log_write/i);for(const action of ['release_created','release_validated','release_activated','release_rolled_back'])assert.match(repairGroup3Sql,new RegExp(`'${action}'`));assert.match(repairGroup3Sql,/insert into public\.audit_logs[\s\S]*'release_activated'/i)})

test('layout hard deletion is locked and rejects immutable history',()=>{assert.match(layoutLifecycleSql,/create or replace function public\.delete_layout_if_safe/i);assert.match(layoutLifecycleSql,/from public\.layouts[\s\S]*for update/i);assert.match(layoutLifecycleSql,/status <> 'draft'/i);assert.match(layoutLifecycleSql,/join public\.layout_versions version on version\.id = release\.layout_version_id/i);assert.match(layoutLifecycleSql,/join public\.layout_versions version on version\.id = workspace\.configuring_layout_version_id/i);assert.match(layoutLifecycleSql,/published or release history and cannot be permanently deleted\. Archive it instead/i)})

test('layout archive preserves versions and release history',()=>{const archive=layoutLifecycleSql.slice(layoutLifecycleSql.indexOf('create or replace function public.archive_layout_document'),layoutLifecycleSql.indexOf('create or replace function public.delete_layout_if_safe'));assert.match(archive,/update public\.layouts[\s\S]*status = 'archived'/i);assert.doesNotMatch(archive,/delete from public\.(layouts|layout_versions|site_releases)/i);assert.match(archive,/'layout_archived'/i)})

test('draft discard is limited to safe non-sole drafts',()=>{assert.match(layoutLifecycleSql,/create or replace function public\.discard_layout_draft_if_safe/i);assert.match(layoutLifecycleSql,/target_version\.status <> 'draft'/i);assert.match(layoutLifecycleSql,/A release-referenced layout version cannot be discarded/i);assert.match(layoutLifecycleSql,/Admin workspace is using this draft/i);assert.match(layoutLifecycleSql,/version_count <= 1/i);assert.match(layoutLifecycleSql,/Only draft layout versions can be discarded\. Published history is immutable/i)})

test('layout lifecycle RPCs are service-role-only and browser deletes are revoked',()=>{for(const signature of ['rename_layout_document\\(uuid, text, text, uuid\\)','archive_layout_document\\(uuid, uuid\\)','delete_layout_if_safe\\(uuid, uuid\\)','discard_layout_draft_if_safe\\(uuid, uuid, uuid\\)']){assert.match(layoutLifecycleSql,new RegExp(`revoke all on function public\\.${signature} from public, anon, authenticated`,'i'));assert.match(layoutLifecycleSql,new RegExp(`grant execute on function public\\.${signature} to service_role`,'i'))}for(const table of ['layouts','layout_versions','layout_pages','layout_validation_results'])assert.match(layoutLifecycleSql,new RegExp(`revoke delete on public\\.${table} from anon, authenticated`,'i'))})
