import test from 'node:test'
import assert from 'node:assert/strict'
import fs from 'node:fs'
import path from 'node:path'
import { spawnSync } from 'node:child_process'
import { fileURLToPath } from 'node:url'

const root = fileURLToPath(new URL('..', import.meta.url))
const read = (file) => fs.readFileSync(path.join(root, file), 'utf8')
const exists = (file) => fs.existsSync(path.join(root, file))

test('canonical StudioNode contract exists only in contracts package', () => {
  const contract = read('packages/contracts/src/index.ts')
  assert.match(contract, /export interface StudioNode\s*{/)
  const candidates = [
    'packages/builder-core/src/editor-state.ts',
    'packages/runtime-renderer/src/index.tsx',
    'apps/studio/src/StudioEditor.tsx',
  ]
  for (const file of candidates) assert.doesNotMatch(read(file), /interface StudioNode\s*{/)
})

test('Studio editor and Admin/Public preview all use the shared runtime renderer', () => {
  const studio = read('apps/studio/src/StudioEditor.tsx')
  const admin = read('apps/admin/src/App.tsx')
  const web = read('apps/web/src/App.tsx')
  assert.match(studio, /RuntimeRenderer/)
  assert.match(studio, /RuntimeSitePreview/)
  assert.match(admin, /RuntimeSitePreview/)
  assert.match(web, /RuntimeSitePreview/)
  assert.equal(exists('apps/studio/src/StudioCanvas.tsx'), false)
})

test('Admin and Studio app themes are independent from layout design tokens', () => {
  const theme = read('packages/ui/src/theme.tsx')
  const admin = read('apps/admin/src/App.tsx')
  const studioApp = read('apps/studio/src/App.tsx')
  const inspector = read('apps/studio/src/Inspector.tsx')
  for (const key of ['--surface-alt','--border-hover','--text-muted','--text-secondary','--primary-hover','--primary-text','--workspace']) assert.match(theme, new RegExp(key.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')))
  assert.match(admin, /portfolio-admin-theme/)
  assert.match(studioApp, /portfolio-studio-theme/)
  assert.match(inspector, /TokensTab/)
  assert.match(inspector, /--site-/)
})

test('API uses authenticated Admin/Studio routers and explicit CORS origins', () => {
  const api = read('apps/api/src/index.ts')
  const auth = read('apps/api/src/lib/auth.ts')
  assert.match(api, /app\.use\('\/api\/studio',\s*studioRouter\)/)
  assert.match(api, /app\.use\('\/api\/admin',\s*adminRouter\)/)
  assert.match(auth, /createRequireAdmin/)
  assert.match(auth, /createRequireStudio/)
  assert.match(api, /allowedOrigins/)
  assert.doesNotMatch(api, /app\.use\(cors\(\)\)/)
})

test('API runtime package entrypoints expose required named values through tsx', () => {
  const script = `
    import { ANIMATION_PRESETS } from '@platform/animation-runtime'
    import { cloneNodeWithFreshIds, createBlankDocument, createCosmicPortfolioTemplate, slugify } from '@platform/builder-core'
    import { LAYOUT_SCHEMA_VERSION, RUNTIME_VERSION } from '@platform/contracts'
    import { createServerSupabaseClients } from '@platform/supabase'
    import { buildContentCompatibility, collectContentSlots, isRuntimeCompatible, validateEditorDocument } from '@platform/validation'
    const required = [cloneNodeWithFreshIds, createBlankDocument, createCosmicPortfolioTemplate, slugify, createServerSupabaseClients, buildContentCompatibility, collectContentSlots, isRuntimeCompatible, validateEditorDocument]
    if (!Array.isArray(ANIMATION_PRESETS) || ANIMATION_PRESETS.length === 0 || required.some(value => typeof value !== 'function') || !LAYOUT_SCHEMA_VERSION || !RUNTIME_VERSION) process.exit(1)
  `
  const result = spawnSync(process.execPath, ['--import', 'tsx', '--input-type=module', '--eval', script], { cwd: root, encoding: 'utf8' })
  assert.equal(result.status, 0, result.stderr || result.stdout)
})

test('release flow has immutable snapshots and only atomic activation', () => {
  const api = read('apps/api/src/index.ts')
  const migration = read('supabase/migrations/20260808000400_repair_group_3_release_integrity.sql')
  assert.match(api, /rpc\('create_site_release'/)
  assert.match(api, /rpc\('record_release_validation'/)
  assert.match(api, /rpc\('activate_release'/)
  assert.match(api, /rpc\('rollback_release'/)
  assert.doesNotMatch(api, /from\('site_releases'\)\.insert/)
  assert.doesNotMatch(api, /from\('site_releases'\)\.update/)
  assert.doesNotMatch(api, /Math\.max\(0,[\s\S]*release_number/)
  assert.match(migration, /create unique index if not exists one_active_site_release/i)
  assert.match(migration, /create or replace function public\.activate_release/i)
  assert.match(migration, /create or replace function public\.rollback_release/i)
  assert.match(migration, /Ready and activated release snapshots are immutable/i)
})

test('Public Web uses clean browser routes and runtime manifest bootstrap', () => {
  const web = read('apps/web/src/App.tsx')
  assert.match(web, /BrowserRouter/)
  assert.doesNotMatch(web, /HashRouter/)
  assert.match(web, /\/api\/public\/runtime/)
  assert.match(web, /linkMode="browser"/)
  assert.match(read('apps/web/vercel.json'), /index\.html/)
})

test('Studio persistence includes pages and immutable publication workflow', () => {
  const api = read('apps/api/src/index.ts')
  const platform = read('apps/api/src/lib/platform.ts')
  const contracts = read('packages/contracts/src/index.ts')
  const migration = read('supabase/migrations/20260808000100_platform_phase5_complete.sql')
  const repairMigration = read('supabase/migrations/20260808000200_repair_group_2_studio_persistence_integrity.sql')
  assert.match(api, /studioRouter\.put\('\/versions\/:id\/document'/)
  assert.match(api, /rpc\('save_layout_document'/)
  assert.match(api, /pages_value: candidate\.pages\.map/)
  assert.match(api, /Published\/archived versions are immutable/)
  assert.match(api, /studioRouter\.post\('\/versions\/:id\/publish'/)
  assert.match(api, /rpc\('publish_layout_version'/)
  assert.match(api, /expected_revision_token: revisionToken/)
  assert.match(platform, /revisionToken: version\.revision_token/)
  assert.match(platform, /revisionToken === version\?\.revision_token/)
  assert.match(contracts, /revisionToken\?: string/)
  assert.match(api, /studioRouter\.post\('\/layouts\/:id\/drafts'/)
  assert.match(migration, /Page % belongs to another layout version/)
  assert.match(migration, /old_version_status/)
  assert.match(migration, /new_version_status/)
  assert.match(repairMigration, /security definer\s+set search_path = pg_catalog, pg_temp/i)
  assert.match(repairMigration, /Draft changed after validation\. Revalidate before publishing/)
})

test('Blank and Cosmic layout creation use one atomic collision-safe RPC', () => {
  const studio = read('apps/studio/src/App.tsx')
  const api = read('apps/api/src/index.ts')
  const migration = read('supabase/migrations/20260808000300_repair_group_2_atomic_layout_creation.sql')
  const route = api.slice(api.indexOf("studioRouter.post('/layouts'"), api.indexOf("studioRouter.get('/layouts/:id/editor'"))
  assert.match(studio, /template==='cosmic'\?'Cosmic Portfolio':'Untitled Layout'/)
  assert.match(route, /rpc\('create_layout_document'/)
  assert.match(route, /pages_value: document\.pages\.map/)
  assert.doesNotMatch(route, /from\('layouts'\)\.insert|from\('layout_versions'\)\.insert|from\('layout_pages'\)\.insert/)
  assert.match(route, /Layout creation failed\. No layout was created\./)
  assert.match(migration, /exception when unique_violation/i)
  assert.match(migration, /layouts_slug_key/i)
})

test('Studio editor deep link hydrates the exact persisted layout version', () => {
  const main = read('apps/studio/src/main.tsx')
  const app = read('apps/studio/src/App.tsx')
  const routing = read('apps/studio/src/routing.ts')
  const api = read('apps/api/src/index.ts')
  assert.match(main, /BrowserRouter/)
  assert.match(routing, /\/layouts\/\$\{encodeURIComponent\(layoutId\)\}\/versions\/\$\{encodeURIComponent\(versionId\)\}\/editor/)
  assert.match(app, /parseStudioEditorRoute\(location\.pathname\)/)
  assert.match(app, /selectedPageFromSearch\(location\.search\)/)
  assert.match(app, /editor\.loadDocument\(document, preferredPageId\)/)
  assert.match(app, /\/api\/studio\/layouts\/\$\{editorRoute\.layoutId\}\/versions\/\$\{editorRoute\.versionId\}\/editor/)
  assert.match(api, /studioRouter\.get\('\/layouts\/:layoutId\/versions\/:versionId\/editor'/)
  assert.match(api, /\.eq\('id', req\.params\.versionId\)\.eq\('layout_id', req\.params\.layoutId\)/)
  assert.match(app, /Returned to the Layout Library/)
})

test('Studio persisted-tree hydration normalizes legacy nodes and has a focused error boundary', () => {
  const builder = read('packages/builder-core/src/editor-state.ts')
  const platform = read('apps/api/src/lib/platform.ts')
  const editor = read('apps/studio/src/StudioEditor.tsx')
  const app = read('apps/studio/src/App.tsx')
  const boundary = read('apps/studio/src/StudioErrorBoundary.tsx')
  assert.match(builder, /normalizeLayoutPageSchema/)
  assert.match(builder, /source\?\.root \?\? source\?\.nodes/)
  assert.match(builder, /normalizeEditorDocument/)
  assert.match(builder, /walkStudioNodes/)
  assert.match(platform, /normalizeLayoutPageSchema\(row\.layout_tree, row\.id\)/)
  assert.match(platform, /return normalizeEditorDocument\(/)
  assert.match(editor, /walkStudioNodes\(page\.schema\.root/)
  assert.doesNotMatch(editor, /const walk=\(nodes:StudioNode\[\]\)=>nodes\.forEach/)
  assert.match(app, /<StudioErrorBoundary/)
  assert.match(boundary, /Studio could not render this layout\./)
  assert.match(boundary, /Back to Layouts/)
  assert.match(boundary, /console\.error\('Studio editor render failed'/)
})

test('Studio Layout Library exposes compact server-authorized lifecycle actions', () => {
  const library = read('apps/studio/src/LayoutLibrary.tsx')
  const app = read('apps/studio/src/App.tsx')
  const api = read('apps/api/src/index.ts')
  assert.match(app, /<LayoutLibrary/)
  assert.match(library, /aria-haspopup="menu"/)
  for (const action of ['Open', 'Rename', 'Delete permanently']) assert.match(library, new RegExp(`label="${action}"`))
  for (const action of ['Duplicate', 'Archive']) assert.match(library, new RegExp(`'${action}'`))
  assert.match(library, /Delete .* permanently\?/)
  assert.match(library, /This action cannot be undone\./)
  assert.match(library, /Discard draft v/)
  assert.match(library, /await onRefresh\(\); await options\.onSuccess\?\.\(value\)/)
  assert.match(library, /data-layout-card=/)
  assert.doesNotMatch(library, /service_role|SUPABASE_SERVICE_ROLE/)
  assert.match(api, /studioRouter\.delete\('\/layouts\/:id', requireAdmin/)
  assert.match(api, /studioRouter\.delete\('\/layouts\/:layoutId\/versions\/:versionId', requireAdmin/)
  assert.match(api, /rpc\('delete_layout_if_safe'/)
  assert.match(api, /rpc\('discard_layout_draft_if_safe'/)
})

test('Studio lifecycle menus close normally and destructive feedback is race-safe', () => {
  const library = read('apps/studio/src/LayoutLibrary.tsx')
  const feedback = read('apps/studio/src/ActionFeedback.tsx')
  const sharedFeedback = read('packages/ui/src/mutation-feedback.tsx')
  assert.match(library, /useMutationActions\(\)/)
  assert.match(library, /Deleting "\$\{target\.layout\.name\}"\.\.\./)
  assert.match(library, /Deleted "\$\{target\.layout\.name\}" permanently\./)
  assert.match(library, /<ActionFeedback feedback=\{actions\.feedback\}/)
  assert.match(library, /if \(!menuId\) return[\s\S]*addEventListener\('pointerdown'[\s\S]*removeEventListener\('pointerdown'/)
  assert.match(library, /isOutsideMenu\(menuRootRef\.current, event\.target\)/)
  assert.match(library, /event\.key === 'Escape'\) setMenuId\(null\)/)
  assert.match(library, /aria-controls=\{menuId === layout\.id/)
  assert.match(library, /onClick=\{\(\) => setMenuId\(\(current\) => current === layout\.id \? null : layout\.id\)\}/)
  assert.match(feedback, /feedbackAutoDismissDelay/)
  assert.match(sharedFeedback, /message\.tone === 'success' \? autoDismissMs : null/)
  assert.match(sharedFeedback, /current === message \? null : current/)
})

test('Batch C1 Studio Layout Library uses shared gates for every lifecycle mutation', () => {
  const library = read('apps/studio/src/LayoutLibrary.tsx')
  for (const key of ['create-blank', 'create-cosmic', 'rename-', 'duplicate-', 'archive-', 'delete-', 'discard-']) assert.match(library, new RegExp(key))
  for (const label of ['Creating...', 'Saving...', 'Duplicating...', 'Archiving...', 'Deleting...', 'Discarding...']) assert.match(library, new RegExp(label.replaceAll('.', '\\.')))
  assert.match(library, /conflictKey: 'layout-creation'/)
  assert.match(library, /conflictKey: `layout-\$\{target\.id\}`/)
  assert.match(library, /aria-busy=/)
  assert.match(library, /useMutationActions\(\)/)
  assert.doesNotMatch(library, /createLifecycleActionGate|service_role|SUPABASE_SERVICE_ROLE/)
})

test('Batch C1 Open remains durable navigation with visible route hydration', () => {
  const app = read('apps/studio/src/App.tsx')
  const library = read('apps/studio/src/LayoutLibrary.tsx')
  assert.match(library, /onClick=\{\(\) => onOpen\(layout\.id\)\}/)
  assert.match(app, /navigate\(studioEditorPath\(id,version\.id\)\)/)
  assert.match(app, /apiFetch<any>\(`\/api\/studio\/layouts\/\$\{editorRoute\.layoutId\}\/versions\/\$\{editorRoute\.versionId\}\/editor`\)/)
  assert.match(app, /Loading Studio…/)
  assert.match(app, /studioEditorPath\(editorRoute\.layoutId, editorRoute\.versionId, editor\.state\.pageId\)/)
})

test('Batch C1 creation still uses atomic API layout creation path', () => {
  const app = read('apps/studio/src/App.tsx')
  const api = read('apps/api/src/index.ts')
  assert.match(app, /apiFetch<any>\('\/api\/studio\/layouts',\{method:'POST'/)
  const createRoute = api.slice(api.indexOf("studioRouter.post('/layouts'"), api.indexOf("studioRouter.get('/layouts/:id/editor'"))
  assert.match(createRoute, /rpc\('create_layout_document'/)
  assert.doesNotMatch(createRoute, /from\('layouts'\)\.insert|from\('layout_versions'\)\.insert/)
})

test('Studio duplicate remains atomic and skips unreadable zero-page versions', () => {
  const api = read('apps/api/src/index.ts')
  const duplicate = api.slice(api.indexOf("studioRouter.post('/layouts/:id/duplicate'"), api.indexOf("studioRouter.put('/versions/:id/document'"))
  assert.match(duplicate, /count:'exact', head:true/)
  assert.match(duplicate, /Layout has no readable version to duplicate/)
  assert.match(duplicate, /rpc\('create_layout_document'/)
  assert.doesNotMatch(duplicate, /from\('layouts'\)\.insert|from\('layout_versions'\)\.insert|from\('layouts'\)\.delete/)
})

test('Studio Canvas, Layers and Inspector share non-persistent node selection', () => {
  const studio = read('apps/studio/src/StudioEditor.tsx')
  const builder = read('packages/builder-core/src/editor-state.ts')
  assert.match(studio, /canvasNodeIdFromTarget\(event\.target\)/)
  assert.match(studio, /event\.stopPropagation\(\);editor\.selectNode/)
  assert.match(studio, /onClick=\{selectCanvasNode\}/)
  assert.match(studio, /selectedNodeId=\{state\.selectedNodeId\}/)
  assert.doesNotMatch(studio, /onNodeClick=\{node=>editor\.selectNode/)
  assert.match(studio, /selected=\{state\.selectedNodeId\} onSelect=\{editor\.selectNode\}/)
  assert.match(studio, /const selected=state\.selectedNodeId\?findNodeById/)
  assert.match(studio, /<Inspector node=\{selected\}/)
  assert.match(studio, /onClick=\{\(\)=>editor\.selectNode\(null\)\}/)
  assert.match(builder, /selectNode: \(id: string \| null\) => setState\(\(prev\) => \(\{ \.\.\.prev, selectedNodeId: id \}\)\)/)
})

test('Studio canvas drag commits validated builder-core tree moves only on drop', () => {
  const studio = read('apps/studio/src/StudioEditor.tsx')
  const builder = read('packages/builder-core/src/editor-state.ts')
  const drag = read('apps/studio/src/canvas-drag.ts')
  assert.match(studio, /canMoveNode, canNodeContainChildren/)
  assert.match(studio, /resolveNodeDropTarget/)
  assert.match(studio, /canvasDropPosition/)
  assert.match(studio, /editor\.moveNode\(nodeId,destination\.parentId,destination\.index\)/)
  assert.match(studio, /onDragEnd:clearDrag/)
  assert.match(studio, /if\(readonly\|\|!node\|\|node\.meta\?\.locked\)return/)
  assert.match(studio, /dropTargetId=\{dragOver\} dropPosition=\{dropPosition\}/)
  assert.doesNotMatch(studio, /removeNodeById|insertNode/)
  assert.match(builder, /export function moveNodeInTree/)
  assert.match(builder, /if \(targetParentId === nodeId\) return 'self-drop'/)
  assert.match(builder, /isDescendant\(root, nodeId, targetParentId\)/)
  assert.match(builder, /if \(node\.meta\?\.locked\) return 'source-locked'/)
  assert.match(builder, /if \(targetParent && !canNodeContainChildren\(targetParent\)\) return 'parent-cannot-contain'/)
  assert.match(builder, /selectedNodeId: nodeId, dirty: true/)
  assert.match(builder, /nextHistory = \[\.\.\.history\.slice\(0, historyIndex \+ 1\), cloneNode\(nextSchema\)\]/)
  assert.match(drag, /if \(canDropInside\) return 'inside'/)
})

test('Studio selection and drop chrome render in an isolated geometry overlay', () => {
  const studio = read('apps/studio/src/StudioEditor.tsx')
  const overlay = read('apps/studio/src/CanvasChromeOverlay.tsx')
  assert.match(studio, /isolation:'isolate',overflow:'visible'/)
  assert.match(studio, /<div ref=\{canvasContentRef\} style=\{\{position:'relative',zIndex:0\}\}/)
  assert.match(studio, /<CanvasChromeOverlay surfaceRef=\{canvasSurfaceRef\}/)
  assert.doesNotMatch(studio, /nodeStyle\.outline|nodeStyle\.borderTop|nodeStyle\.borderBottom|nodeStyle\.resize/)
  assert.doesNotMatch(studio, /<RuntimeRenderer[^>]*selectedNodeId=/)
  assert.match(overlay, /data-studio-canvas-overlay/)
  assert.match(overlay, /data-studio-overlay="selection"/)
  assert.match(overlay, /data-studio-overlay="drop-inside"/)
  assert.match(overlay, /data-studio-overlay=\{`drop-\$\{dropPosition\}`\}/)
  assert.match(overlay, /pointerEvents:'none'/)
  assert.match(overlay, /getBoundingClientRect\(\)/)
  assert.match(overlay, /ResizeObserver/)
  assert.match(overlay, /MutationObserver/)
  assert.match(overlay, /window\.addEventListener\('scroll', schedule, true\)/)
})

test('Studio action feedback, panels and responsive toolbar remain accessible', () => {
  const studio = read('apps/studio/src/StudioEditor.tsx')
  const feedback = read('packages/ui/src/mutation-feedback.tsx')
  const chrome = read('apps/studio/src/studio-chrome.ts')
  assert.match(studio, /Layout saved successfully/)
  assert.match(studio, /Layout could not be saved\. Review the document and try again\./)
  assert.match(studio, /Layout is valid and ready to publish/)
  assert.match(studio, /Validation completed with issues/)
  assert.match(studio, /Layout version published successfully/)
  assert.match(studio, /isPending\('editor-save'\)\?'Saving\.\.\.'/)
  assert.match(studio, /isPending\('editor-validate'\)\?'Validating\.\.\.'/)
  assert.match(studio, /isPending\('editor-publish'\)\?'Publishing\.\.\.'/)
  assert.match(feedback, /data-action-feedback/)
  assert.match(feedback, /message\.tone === 'success' \? autoDismissMs : null/)
  assert.match(feedback, /feedbackAutoDismissDelay\(message, autoDismissMs\)[\s\S]*setTimeout/)
  assert.match(feedback, /role=\{error \? 'alert' : 'status'\}/)
  assert.match(studio, /toggleStudioPanel\(current,'left'\)/)
  assert.match(studio, /toggleStudioPanel\(current,'right'\)/)
  assert.match(studio, /data-studio-edge-toggle=\{side\}/)
  assert.match(studio, /Collapse left panel.*Expand left panel/)
  assert.match(studio, /Collapse inspector.*Expand inspector/)
  assert.match(studio, /data-studio-panel="inspector"/)
  assert.match(studio, /const selected=state\.selectedNodeId\?findNodeById/)
  assert.match(studio, /data-studio-toolbar-primary/)
  assert.match(studio, /data-studio-toolbar-overflow/)
  assert.match(studio, /toolbarMode==='wide'\?secondaryTools\(false\)/)
  assert.match(studio, /Save\*.*Validate.*Publish/)
  assert.match(studio, /data-studio-canvas style=\{\{flex:1,minWidth:0/)
  assert.match(chrome, /if \(width >= 1500\) return 'wide'/)
  assert.match(chrome, /if \(width >= 900\) return 'compact'/)
})

test('Batch C2 Studio Editor gates every direct API action through shared infrastructure', () => {
  const studio = read('apps/studio/src/StudioEditor.tsx')
  assert.match(studio, /useMutationActions\(\)/)
  assert.match(studio, /const EDITOR_API_CONFLICT='studio-editor-api-action'/)
  for (const key of ['editor-save', 'editor-validate', 'editor-publish', 'editor-create-draft', 'editor-create-', 'editor-duplicate-layout', 'editor-archive-layout']) assert.match(studio, new RegExp(key))
  for (const label of ['Saving...', 'Validating...', 'Publishing...', 'Creating draft...', 'Duplicating...', 'Archiving...']) assert.match(studio, new RegExp(label.replaceAll('.', '\\.')))
  assert.match(studio, /aria-busy=/)
  assert.doesNotMatch(studio, /StudioActionGate|actionGateRef|draftBusy/)
  assert.doesNotMatch(studio, /service_role|SUPABASE_SERVICE_ROLE/)
})

test('Batch C2 preserves atomic Save and exact-version Publish without production activation', () => {
  const studio = read('apps/studio/src/StudioEditor.tsx')
  const workflow = read('apps/studio/src/editor-actions.ts')
  const api = read('apps/api/src/index.ts')
  assert.match(studio, /\/api\/studio\/versions\/\$\{state\.versionId\}\/document/)
  assert.match(studio, /publishLayoutAndRefresh\(/)
  assert.match(workflow, /await save\(\)[\s\S]*await publish\(\)[\s\S]*markPublished\(result\)[\s\S]*await refresh\(\)/)
  assert.match(workflow, /LayoutPublishedRefreshError/)
  const saveRoute = api.slice(api.indexOf("studioRouter.put('/versions/:id/document'"), api.indexOf("studioRouter.post('/versions/:id/validate'"))
  const publishRoute = api.slice(api.indexOf("studioRouter.post('/versions/:id/publish'"), api.indexOf("studioRouter.patch('/layouts/:id/rename'"))
  assert.match(saveRoute, /rpc\('save_layout_document'/)
  assert.match(publishRoute, /rpc\('publish_layout_version'/)
  assert.match(publishRoute, /expected_revision_token: revisionToken/)
  assert.doesNotMatch(studio + publishRoute, /activate_site_release|\/releases\/.*activate/)
})

test('Batch C2 validation issues remain controlled and published versions remain immutable', () => {
  const studio = read('apps/studio/src/StudioEditor.tsx')
  assert.match(studio, /validationResultFromError\(error\)/)
  assert.match(studio, /role=\{validationResult\.valid\?'status':'alert'\}/)
  assert.match(studio, /Validation issues/)
  assert.match(studio, /\{!readonly&&<><button[^\n]+editor-save/)
  assert.match(studio, /\{readonly&&<button[^\n]+editor-create-draft/)
})

test('Batch C2 Create Draft keeps canonical existing-draft reuse and duplicate protection', () => {
  const studio = read('apps/studio/src/StudioEditor.tsx')
  const api = read('apps/api/src/index.ts')
  const draftRoute = api.slice(api.indexOf("studioRouter.post('/layouts/:id/drafts'"), api.indexOf("studioRouter.post('/layouts/:id/duplicate'"))
  assert.match(studio, /key:'editor-create-draft',conflictKey:EDITOR_API_CONFLICT/)
  assert.match(studio, /Creating draft\.\.\./)
  assert.match(draftRoute, /const existingDraft =/)
  assert.match(draftRoute, /if \(existingDraft\) return res\.json/)
  assert.ok(draftRoute.indexOf('if (existingDraft)') < draftRoute.indexOf("from('layout_versions').insert"))
})

test('Batch C2 excludes local-only editor controls from network action state', () => {
  const studio = read('apps/studio/src/StudioEditor.tsx')
  assert.match(studio, /setPreview\(true\)/)
  assert.match(studio, /<AppThemeSelector/)
  assert.match(studio, /editor\.addPage/)
  assert.match(studio, /editor\.reorderPage/)
  assert.match(studio, /editor\.duplicatePage/)
  assert.match(studio, /editor\.setZoom/)
  assert.match(studio, /editor\.undo/)
  assert.match(studio, /editor\.setMode/)
  assert.doesNotMatch(studio, /apiFetch[^\n]+(setPreview|setZoom|setMode|addPage|reorderPage|duplicatePage)/)
})

test('Admin Site Content publish uses shared synchronous mutation feedback', () => {
  const admin = read('apps/admin/src/App.tsx')
  const visualContent = admin.slice(admin.indexOf('function VisualContent'), admin.indexOf('function RuntimeSingle'))
  assert.match(admin, /ActionFeedback,[\s\S]*useMutationActions,[\s\S]*from "@platform\/ui"/)
  assert.match(visualContent, /const contentActions = useMutationActions\(\)/)
  assert.match(visualContent, /key: "publish-content"/)
  assert.match(visualContent, /const revisionId = ctx\.revision\.id/)
  assert.match(visualContent, /publishContentAndRefresh\(/)
  assert.match(visualContent, /\/content-revisions\/\$\{revisionId\}\/publish/)
  assert.match(visualContent, /createNextDraft: createContentDraft/)
  assert.match(visualContent, /loadEditorContext/)
  assert.match(visualContent, /ContentPublishedRefreshError/)
  assert.match(visualContent, /Reload Editor/)
  assert.match(visualContent, /publishingContent \? "Publishing\.\.\." : "Publish Content"/)
  assert.match(visualContent, /aria-busy=\{publishingContent\}/)
  assert.match(visualContent, /disabled=\{[\s\S]*contentActionPending/)
  assert.match(visualContent, /<ActionFeedback[\s\S]*feedback=\{contentActions\.feedback\}/)

  const feedback = read('packages/ui/src/mutation-feedback.tsx')
  assert.match(feedback, /finally \{\s*try \{\s*runtime\.setPending\(options\.key, false\)/)
  assert.match(feedback, /finally \{\s*runtime\.gate\.end\(gateKey\)/)
  assert.match(feedback, /const mountedRef = React\.useRef\(false\)/)
})

test('Batch A auth actions use shared synchronous gates and visible shell logout', () => {
  const adminAuth = read('apps/admin/src/AuthGate.tsx')
  const admin = read('apps/admin/src/App.tsx')
  const studioAuth = read('apps/studio/src/AuthGate.tsx')
  const studio = read('apps/studio/src/App.tsx')
  for (const source of [adminAuth, studioAuth]) {
    assert.match(source, /useMutationActions\(\)/)
    assert.match(source, /pending: 'Signing in\.\.\.'/)
    assert.match(source, /pending: 'Signing out\.\.\.'/)
    assert.match(source, /signInWithPassword/)
    assert.match(source, /auth\.signOut\(\)/)
    assert.match(source, /disabled=\{signingIn\}/)
    assert.match(source, /aria-busy=\{signingIn\}/)
    assert.match(source, /Signing in\.\.\./)
    assert.match(source, /role="alert"/)
  }
  assert.match(adminAuth, /conflictKey: 'admin-auth'/)
  assert.match(studioAuth, /conflictKey: 'studio-auth'/)
  assert.match(admin, /auth\?\.signingOut \? "Signing out\.\.\." : "Logout"/)
  assert.match(studio, /auth\?\.signingOut\?'Signing out\.\.\.':'Logout'/)
})

test('Admin Site Content Save Draft uses shared gated feedback and local Preview stays synchronous', () => {
  const admin = read('apps/admin/src/App.tsx')
  const visualContent = admin.slice(admin.indexOf('function VisualContent'), admin.indexOf('function RuntimeSingle'))
  const editValue = admin.slice(admin.indexOf('function EditValue'), admin.indexOf('function MediaPicker'))
  assert.match(visualContent, /key: `save-content-\$\{key\}`/)
  assert.match(visualContent, /conflictKey: "content-revision-action"/)
  assert.match(visualContent, /pending: "Saving draft\.\.\."/)
  assert.match(visualContent, /success: "Draft saved successfully\."/)
  assert.match(visualContent, /contentActions\.isPending\(`save-content-\$\{key\}`\)/)
  assert.match(editValue, /aria-busy=\{saving\}/)
  assert.match(editValue, /saving \? "Saving\.\.\." : "Save Draft"/)
  assert.match(visualContent, /setPreviewMode\(true\)/)
  assert.doesNotMatch(visualContent, /apiFetch[^\n]*previewMode/)
})

test('Batch D closes the remaining control-level pending gaps', () => {
  const admin = read('apps/admin/src/App.tsx')
  const library = read('apps/studio/src/LayoutLibrary.tsx')
  const studioApp = read('apps/studio/src/App.tsx')
  const crud = admin.slice(admin.indexOf('function Crud'), admin.indexOf('function Field'))
  const visualContent = admin.slice(admin.indexOf('function VisualContent'), admin.indexOf('function RuntimeSingle'))
  assert.match(crud, /<button type="button" style=\{B\} onClick=\{\(\) => setEditing\(null\)\}>/)
  assert.match(visualContent, /key: `save-content-\$\{key\}`,[\s\S]*conflictKey: "content-revision-action"/)
  assert.match(visualContent, /actionPending=\{contentActionPending\}/)
  assert.match(library, /onSuccess: \(\) => setRenameLayout\(null\)/)
  assert.match(library, /onSuccess: \(\) => setConfirmation\(null\)/)
  assert.match(library, /busy=\{actions\.isPending\(`duplicate-/)
  assert.match(library, /pending=\{actions\.isPending\(`delete-/)
  const archive = studioApp.slice(studioApp.indexOf('const archiveLayout='), studioApp.indexOf('if(loading'))
  assert.ok(archive.indexOf('await refreshLayouts()') < archive.indexOf("navigate('/')"))
})

test('Batch B1 structured managers gate only real Projects, Notes and Experience writes', () => {
  const admin = read('apps/admin/src/App.tsx')
  const crud = admin.slice(admin.indexOf('function Crud'), admin.indexOf('function Field'))
  for (const resource of ['projects', 'notes', 'experience']) assert.match(crud, new RegExp(`"${resource}"`))
  assert.match(crud, /const structuredActions = useMutationActions\(\)/)
  assert.match(crud, /method: editing\.id \? "PATCH" : "POST"/)
  assert.match(crud, /method: "DELETE"/)
  assert.match(crud, /if \(!confirm\("Delete this record\?"\)\) return/)
  assert.match(crud, /<form onSubmit=\{save\}>/)
  assert.match(crud, /type="submit"/)
  assert.match(crud, /conflictKey: `\$\{resource\}-record-\$\{recordId\}`/)
  assert.match(crud, /structuredActions\.isConflictPending\(`\$\{resource\}-record-/)
  assert.match(crud, /\? editing\.id \? "Saving\.\.\." : "Creating\.\.\."/)
  assert.match(crud, /\? "Deleting\.\.\." : "Delete"/)
  assert.match(crud, /aria-busy=/)
  assert.match(crud, /<ActionFeedback feedback=\{structuredActions\.feedback\}/)
  assert.doesNotMatch(crud, /service_role|SUPABASE_SERVICE_ROLE/)
})

test('Batch B1 has no separate publish or archive request outside scoped form saves', () => {
  const admin = read('apps/admin/src/App.tsx')
  const crud = admin.slice(admin.indexOf('function Crud'), admin.indexOf('function Field'))
  assert.doesNotMatch(crud, /apiFetch\([^)]*\/(publish|archive)/)
  assert.match(admin, /\["published", "boolean"\]/)
})

test('Batch B2 AI Apps uses the shared form and per-record mutation gates', () => {
  const admin = read('apps/admin/src/App.tsx')
  const crud = admin.slice(admin.indexOf('function Crud'), admin.indexOf('function Field'))
  assert.match(crud, /\["projects", "notes", "experience", "apps"\]\.includes\(resource\)/)
  assert.match(crud, /key: actionKey/)
  assert.match(crud, /conflictKey: `\$\{resource\}-record-\$\{recordId\}`/)
  assert.match(crud, /<form onSubmit=\{save\}>/)
  assert.match(crud, /"Saving\.\.\." : "Creating\.\.\."/)
  assert.match(crud, /"Deleting\.\.\." : "Delete"/)
  assert.doesNotMatch(crud, /apiFetch\([^)]*\/(publish|archive)/)
})

test('Batch B2 Media upload and delete use independent shared mutation gates', () => {
  const admin = read('apps/admin/src/App.tsx')
  const media = admin.slice(admin.indexOf('function MediaManager'))
  assert.match(media, /const mediaActions = useMutationActions\(\)/)
  assert.match(media, /key: "media-upload"/)
  assert.match(media, /conflictKey: "media-upload"/)
  assert.match(media, /pending: "Uploading media\.\.\."/)
  assert.match(media, /success: \(result: any\) => result\.refreshed/)
  assert.match(media, /"Media uploaded successfully\."/)
  assert.match(media, /"Media uploaded successfully, but the library could not refresh\."/)
  assert.match(media, /apiFetch\("\/api\/admin\/media\/upload"/)
  assert.match(media, /accept="image\/\*,video\/\*,audio\/\*,\.pdf,\.txt"/)
  assert.match(media, /key: `delete-media-\$\{record\.id\}`/)
  assert.match(media, /conflictKey: `media-record-\$\{record\.id\}`/)
  assert.match(media, /pending: "Deleting media\.\.\."/)
  assert.match(media, /success: \(result: any\) => result\.refreshed/)
  assert.match(media, /"Media deleted successfully\."/)
  assert.match(media, /"Media deleted successfully, but the library could not refresh\."/)
  assert.match(media, /if \(!confirm\("Delete this media file and its metadata\?[^\n]+\)\) return/)
  assert.match(media, /uploading \? "Uploading\.\.\." : "Upload Media"/)
  assert.match(media, /\? "Deleting\.\.\." : "Delete media"/)
  assert.match(media, /aria-busy=/)
  assert.match(media, /<ActionFeedback feedback=\{mediaActions\.feedback\}/)
  assert.doesNotMatch(media, /service_role|SUPABASE_SERVICE_ROLE/)
})

test('Batch B2 Media has no explicit refresh, replace, rename, or metadata mutation control', () => {
  const admin = read('apps/admin/src/App.tsx')
  const media = admin.slice(admin.indexOf('function MediaManager'))
  assert.doesNotMatch(media, />\s*(Refresh|Reload|Replace|Rename)\s*</)
  assert.doesNotMatch(media, /method: "(PUT|PATCH)"/)
})

test('Repair Group 4B2 Admin structured media controls persist canonical IDs', () => {
  const admin = read('apps/admin/src/App.tsx')
  const api = read('apps/api/src/index.ts')
  const normalization = read('apps/api/src/lib/structured-media.ts')
  assert.match(admin, /\["thumbnail_media_id", "media"\]/)
  assert.match(admin, /\["gallery_media_ids", "media-array"\]/)
  assert.match(admin, /\["cover_media_id", "media"\]/)
  assert.match(admin, /\["icon_media_id", "media"\]/)
  assert.doesNotMatch(admin.slice(admin.indexOf('experience: {'), admin.indexOf('apps: {')), /logo_media_id/)
  assert.match(api, /normalizeStructuredMediaInput/)
  assert.match(api, /replaceProjectGallery/)
  assert.match(normalization, /body\[legacyField\] = data\.public_url/)
  assert.doesNotMatch(normalization, /service_role|SUPABASE_SERVICE_ROLE_KEY/)
})

test('Batch B3 Admin Layout Preview and Configure use narrow shared action gates', () => {
  const admin = read('apps/admin/src/App.tsx')
  const layouts = admin.slice(admin.indexOf('function Layouts'), admin.indexOf('function Mini'))
  assert.match(layouts, /const layoutActions = useMutationActions\(\)/)
  assert.match(layouts, /key: `preview-layout-\$\{v\}`/)
  assert.match(layouts, /pending: "Loading layout preview\.\.\."/)
  assert.match(layouts, /key: `configure-layout-\$\{v\}`/)
  assert.match(layouts, /conflictKey: "layout-configuration"/)
  assert.match(layouts, /pending: "Configuring layout\.\.\."/)
  assert.match(layouts, /method: "POST"/)
  assert.match(layouts, /"Loading Preview\.\.\." : "Preview"/)
  assert.match(layouts, /"Configuring\.\.\." : "Configure Content"/)
  assert.match(layouts, /aria-busy=/)
  assert.match(layouts, /<ActionFeedback feedback=\{layoutActions\.feedback\}/)
  assert.doesNotMatch(layouts, /activate|rollback|site_releases|service_role/i)
})

test('Batch B3 Settings Save uses one form-backed shared mutation gate', () => {
  const admin = read('apps/admin/src/App.tsx')
  const settings = admin.slice(admin.indexOf('function Settings'), admin.indexOf('function Layouts'))
  assert.match(settings, /const settingsActions = useMutationActions\(\)/)
  assert.match(settings, /<form onSubmit=\{saveSetting\}/)
  assert.match(settings, /type="submit"/)
  assert.match(settings, /key: `save-setting-\$\{settingKey\}`/)
  assert.match(settings, /conflictKey: `setting-\$\{settingKey\}`/)
  assert.match(settings, /pending: "Saving setting\.\.\."/)
  assert.match(settings, /success: "Setting saved successfully\."/)
  assert.match(settings, /method: "PUT"/)
  assert.match(settings, /savingSetting \? "Saving\.\.\." : "Save"/)
  assert.match(settings, /aria-busy=\{savingSetting\}/)
  assert.match(settings, /<ActionFeedback feedback=\{settingsActions\.feedback\}/)
  assert.doesNotMatch(settings, /service_role|SUPABASE_SERVICE_ROLE/)
})

test('Batch B3 Release audit preserves shared labels and transition conflict gate', () => {
  const releases = read('apps/admin/src/ReleaseManager.tsx')
  for (const label of ['Creating...', 'Loading Preview...', 'Validating...', 'Activating...', 'Rolling back...']) assert.match(releases, new RegExp(label.replaceAll('.', '\\.')))
  assert.equal((releases.match(/conflictKey: 'release-mutation'/g) || []).length, 4)
  assert.match(releases, /key: `preview-\$\{release\.id\}`/)
  assert.match(releases, /<ActionFeedback feedback=\{actions\.feedback\}/)
  assert.match(releases, /aria-busy=/)
  assert.doesNotMatch(releases, /service_role|SUPABASE_SERVICE_ROLE/)
})

test('Admin Release Manager uses shared gated feedback for every RG3 action', () => {
  const releases = read('apps/admin/src/ReleaseManager.tsx')
  assert.match(releases, /ActionFeedback, useMutationActions/)
  assert.match(releases, /const actions = useMutationActions\(\)/)
  for (const action of ['create', 'validate-', 'activate-', 'rollback-']) assert.match(releases, new RegExp(`key: [^\\n]*${action}`))
  assert.equal((releases.match(/conflictKey: 'release-mutation'/g) || []).length, 4)
  for (const label of ['Creating...', 'Validating...', 'Activating...', 'Rolling back...', 'Loading Preview...']) assert.match(releases, new RegExp(label.replaceAll('.', '\\.')))
  assert.equal((releases.match(/aria-busy=/g) || []).length, 5)
  assert.match(releases, /<ActionFeedback feedback=\{actions\.feedback\} onDismiss=\{actions\.dismiss\}/)
  assert.doesNotMatch(releases, /const \[busy, setBusy\]|const \[message, setMessage\]|const \[error, setError\]/)
})

test('Studio Back to Layouts is primary, deterministic and dirty-safe', () => {
  const app = read('apps/studio/src/App.tsx')
  const studio = read('apps/studio/src/StudioEditor.tsx')
  const routing = read('apps/studio/src/routing.ts')
  assert.match(routing, /export function studioLayoutsPath\(\): string \{\s*return '\/'/)
  assert.match(app, /navigate\(studioLayoutsPath\(\)\)/)
  assert.match(app, /onBackToLayouts=\{backToLayouts\}/)
  assert.match(studio, /aria-label="Back to Layouts" title="Back to Layouts"/)
  assert.match(studio, /toolbarMode==='narrow'\?'←':'← Layouts'/)
  assert.match(studio, /backToLayoutsRequiresConfirmation\(state\.dirty\)/)
  assert.match(studio, /You have unsaved changes\. Leave without saving\?/)
  assert.match(studio, />Stay<.*>Leave without saving</)
  assert.match(studio, /setLeavePrompt\(false\);onBackToLayouts\(\)/)
  assert.doesNotMatch(studio, /history\.back\(|navigate\(-1\)/)
})

test('Studio protected requests always use the current refreshable Supabase session', () => {
  const api = read('apps/studio/src/api.ts')
  const auth = read('apps/studio/src/auth.ts')
  const gate = read('apps/studio/src/AuthGate.tsx')
  const request = read('apps/studio/src/authenticated-request.ts')
  const app = read('apps/studio/src/App.tsx')
  const editor = read('apps/studio/src/StudioEditor.tsx')
  assert.match(api, /authenticatedJsonRequest<T>\(`\$\{API_URL\}\$\{path\}`, options, getCurrentStudioSession\)/)
  assert.doesNotMatch(api, /sessionStorage|getItem\('portfolio-access-token'\)/)
  assert.doesNotMatch(gate, /sessionStorage\.setItem|portfolio-access-token.*access_token/)
  assert.match(auth, /let browserClient: SupabaseClient \| null \| undefined/)
  assert.match(auth, /await auth\.getSession\(\)/)
  assert.match(auth, /await auth\.refreshSession\(\)/)
  assert.match(auth, /sessionNeedsRefresh/)
  assert.match(gate, /onAuthStateChange/)
  assert.match(gate, /STUDIO_SESSION_EXPIRED_MESSAGE/)
  assert.match(request, /for \(let attempt = 0; attempt < 2; attempt \+= 1\)/)
  assert.match(request, /sessionProvider\(attempt === 1\)/)
  assert.match(request, /Authorization: `Bearer \$\{session\.access_token\}`/)
  assert.match(app, /apiFetch<any>\('\/api\/studio\/layouts'/)
  assert.match(editor, /versions\/\$\{state\.versionId\}\/document/)
  assert.match(editor, /versions\/\$\{state\.versionId\}\/validate/)
  assert.match(editor, /const versionId=state\.versionId[\s\S]*versions\/\$\{versionId\}\/publish/)
  for (const source of [api, auth, gate, request, app, editor]) assert.doesNotMatch(source, /SUPABASE_SERVICE_ROLE_KEY/)
})

test('Admin implements layout gallery, visual content editor and release preview', () => {
  const admin = read('apps/admin/src/App.tsx')
  const releases = read('apps/admin/src/ReleaseManager.tsx')
  assert.match(admin, /function Layouts/)
  assert.match(admin, /function VisualContent/)
  assert.match(admin, /<ReleaseManager\s*\/>/)
  assert.match(releases, /function ReleasePreview/)
  assert.match(admin, /Content Inspector/)
  assert.match(admin, /Save Draft/)
  assert.match(admin, /Configure/)
})

test('environment secrets are gitignored and example files are provided', () => {
  const gitignore = read('.gitignore')

  assert.match(gitignore, /^\.env\*$/m)
  assert.match(gitignore, /^!\.env\.example$/m)

  for (const dir of ['apps/api', 'apps/web', 'apps/admin', 'apps/studio']) {
    assert.equal(exists(path.join(dir, '.env.example')), true)
  }
})


test('Admin visual content editor can inspect site settings and structured collections', () => {
  const admin = read('apps/admin/src/App.tsx')
  const renderer = read('packages/runtime-renderer/src/index.tsx')
  assert.match(admin, /b\.type\s*===\s*["']collection["']/)
  assert.match(admin, /Manage \{pretty\(b\.collection\)\}/)
  assert.match(admin, /Open Settings/)
  assert.match(renderer, /binding\.type === 'content' \|\| binding\.type === 'setting' \|\| binding\.type === 'collection'/)
})

test('workspace imports shared packages through declared package entrypoints', () => {
  for (const file of ['apps/api/src/index.ts','apps/studio/src/Inspector.tsx']) assert.doesNotMatch(read(file), /@platform\/builder-core\/animations/)
  assert.match(read('packages/builder-core/src/index.ts'), /export \* from '\.\/animations'/)
  assert.match(read('apps/api/src/index.ts'), /ANIMATION_PRESETS \} from '@platform\/animation-runtime'/)
})

test('release UI distinguishes activation from rollback', () => {
  const releases = read('apps/admin/src/ReleaseManager.tsx')
  assert.doesNotMatch(releases, /Activate \/ Rollback/)
  assert.match(releases, /release\.status === 'draft'[\s\S]*Validate/)
  assert.match(releases, /release\.status === 'ready'[\s\S]*Activate/)
  assert.match(releases, /release\.status === 'superseded'[\s\S]*Rollback/)
})

test('release preview is read-only and readiness requires explicit validation', () => {
  const api = read('apps/api/src/index.ts')
  const preview = api.slice(api.indexOf("adminRouter.post('/releases/:id/preview'"), api.indexOf("adminRouter.post('/releases/:id/activate'"))
  assert.match(api, /adminRouter\.post\('\/releases\/:id\/validate'/)
  assert.match(preview, /validateRelease\(supabaseAdmin, release\)/)
  assert.doesNotMatch(preview, /record_release_validation|site_releases'\)\.update/)
})

test('Public Web resolves only the active release through the platform API', () => {
  const platform = read('apps/api/src/lib/platform.ts')
  const studio = read('apps/api/src/index.ts').slice(read('apps/api/src/index.ts').indexOf('// Studio APIs'), read('apps/api/src/index.ts').indexOf('// Admin CRUD'))
  assert.match(platform, /from\('site_releases'\)\.select\('\*'\)\.eq\('status', 'active'\)\.maybeSingle\(\)/)
  assert.doesNotMatch(studio, /rpc\('(activate_release|rollback_release)'/)
  assert.doesNotMatch(studio, /from\('site_releases'\)\.(insert|update|delete)/)
})


test('Admin Site Content tabs use RuntimeRoute.pageId rather than a nonexistent route id', () => {
  const admin = read('apps/admin/src/App.tsx')
  assert.match(admin, /ordinary\.map\(\(route\)\s*=>\s*\(\{[\s\S]*id:\s*route\.pageId,[\s\S]*name:\s*route\.name,[\s\S]*schema:\s*route\.schema/)
  assert.match(admin, /previewMode\s*\?\s*manifest\s*:\s*\{\s*\.\.\.manifest,\s*globals:\s*\{\}\s*\}/)
})
