import React from 'react'
import {BrowserRouter,useLocation,useNavigate} from 'react-router-dom'
import type {RuntimeManifest,RuntimeRoute} from '@platform/contracts'
import {RuntimeSitePreview} from '@platform/runtime-renderer'
import {createBrowserSupabaseClient} from '@platform/supabase'
import {publicFetch} from './api'

export default function App(){return <BrowserRouter><RuntimeApp/></BrowserRouter>}
function RuntimeApp(){const location=useLocation();const [manifest,setManifest]=React.useState<RuntimeManifest|null>(null),[error,setError]=React.useState(''),[loading,setLoading]=React.useState(true);React.useEffect(()=>{publicFetch<any>('/api/public/runtime').then(r=>setManifest(r.data)).catch(e=>setError(e.message)).finally(()=>setLoading(false))},[]);if(location.pathname==='/login')return <AuthPage mode="login"/>;if(location.pathname==='/register')return <AuthPage mode="register"/>;if(location.pathname.startsWith('/dashboard'))return <Dashboard/>;if(loading)return <Fallback>Loading portfolio…</Fallback>;if(error||!manifest)return <Fallback><div><h1>No active portfolio release</h1><p>{error||'Create and activate a release from Admin.'}</p></div></Fallback>;const match=matchRoute(manifest.routes,location.pathname);if(!match)return <Fallback><div><h1>404</h1><p>This route is not part of the active layout.</p></div></Fallback>;const {route,params}=match;return <RenderedRuntimeRoute manifest={manifest} route={route} params={params}/>} 
function RenderedRuntimeRoute({manifest,route,params}:{manifest:RuntimeManifest;route:RuntimeRoute;params:Record<string,string>}){const fieldContext=getFieldContext(manifest,route,params);useSeo(route,fieldContext);const mode=useResponsiveMode();if(route.pageType==='collection_detail'&&!fieldContext)return <Fallback><div><h1>404</h1><p>This item is not available in the active release.</p></div></Fallback>;return <RuntimeSitePreview manifest={manifest} route={route} mode={mode} fieldContext={fieldContext} linkMode="browser"/>}
function compilePath(pattern:string){const names:string[]=[];const escaped=pattern.replace(/\//g,'\\/').replace(/:([A-Za-z0-9_]+)/g,(_m,n)=>{names.push(n);return '([^\\/]+)'});return{regex:new RegExp(`^${escaped}/?$`),names}}
function matchRoute(routes:RuntimeRoute[],pathname:string){for(const route of routes){const {regex,names}=compilePath(route.path||'/');const m=pathname.match(regex);if(m)return{route,params:Object.fromEntries(names.map((n,i)=>[n,decodeURIComponent(m[i+1])]))}}return null}
function getFieldContext(manifest:RuntimeManifest,route:RuntimeRoute,params:Record<string,string>){if(route.pageType!=='collection_detail'||!route.collectionName)return undefined;return (manifest.collections[route.collectionName]||[]).find((x:any)=>String(x.slug||x.id)===String(params.slug||params.id)) as Record<string,unknown>|undefined}
function useSeo(route:RuntimeRoute,field?:Record<string,unknown>){React.useEffect(()=>{const seo=route.seo||{};const title=String(field?.title||field?.name||seo.title||route.name||'Portfolio');const desc=String(field?.summary||field?.short_description||seo.description||'');const image=String(field?.cover_image||field?.thumbnail||seo.ogImage||seo.og_image||'');document.title=title;const setMeta=(selector:string,attr:'name'|'property',key:string,value:string)=>{let el=document.querySelector(selector) as HTMLMetaElement|null;if(!el){el=document.createElement('meta');el.setAttribute(attr,key);document.head.appendChild(el)}el.content=value};setMeta('meta[name="description"]','name','description',desc);setMeta('meta[property="og:title"]','property','og:title',title);setMeta('meta[property="og:description"]','property','og:description',desc);if(image)setMeta('meta[property="og:image"]','property','og:image',image);setMeta('meta[name="robots"]','name','robots',seo.noindex?'noindex,nofollow':'index,follow');let canonical=document.querySelector('link[rel="canonical"]') as HTMLLinkElement|null;if(!canonical){canonical=document.createElement('link');canonical.rel='canonical';document.head.appendChild(canonical)}canonical.href=String(seo.canonical||`${window.location.origin}${window.location.pathname}`)},[route,field])}
function useResponsiveMode(){const calc=()=>window.innerWidth<600?'mobile':window.innerWidth<1000?'tablet':'desktop';const [mode,setMode]=React.useState<'desktop'|'tablet'|'mobile'>(calc);React.useEffect(()=>{const h=()=>setMode(calc());window.addEventListener('resize',h);return()=>window.removeEventListener('resize',h)},[]);return mode}
function supabase(){const url=import.meta.env.VITE_SUPABASE_URL,key=import.meta.env.VITE_SUPABASE_ANON_KEY;if(!url||!key)throw new Error('Supabase frontend environment variables are missing.');return createBrowserSupabaseClient(url,key)}
function AuthPage({mode}:{mode:'login'|'register'}){const nav=useNavigate(),[email,setEmail]=React.useState(''),[password,setPassword]=React.useState(''),[message,setMessage]=React.useState('');const submit=async(e:React.FormEvent)=>{e.preventDefault();try{const s=supabase();if(mode==='login'){const {error}=await s.auth.signInWithPassword({email,password});if(error)throw error;nav('/dashboard')}else{const {error}=await s.auth.signUp({email,password});if(error)throw error;setMessage('Registration created. Verify your email if verification is enabled.')}}catch(e:any){setMessage(e.message)}};return <Fallback><form onSubmit={submit} style={card}><h1>{mode==='login'?'Sign in':'Create account'}</h1><input style={input} type="email" required value={email} onChange={e=>setEmail(e.target.value)} placeholder="Email"/><input style={input} type="password" minLength={8} required value={password} onChange={e=>setPassword(e.target.value)} placeholder="Password"/><button style={button}>{mode==='login'?'Sign in':'Register'}</button>{message&&<p>{message}</p>}<a href={mode==='login'?'/register':'/login'}>{mode==='login'?'Create account':'Already registered?'}</a></form></Fallback>}
function Dashboard(){const nav=useNavigate(),[user,setUser]=React.useState<any>(null);React.useEffect(()=>{try{supabase().auth.getUser().then(({data})=>{if(!data.user)nav('/login');else setUser(data.user)})}catch{nav('/login')}},[nav]);return <Fallback><div style={{...card,width:'min(720px,90vw)'}}><h1>User Dashboard</h1><p>Signed in as {user?.email||'…'}</p><nav style={{display:'flex',gap:8,flexWrap:'wrap'}}><span style={pill}>Resumes</span><span style={pill}>History</span><span style={pill}>Settings</span></nav><p style={{color:'#64748b'}}>AI execution remains deferred; this authenticated shell is ready for the future agent platform.</p><button style={button} onClick={async()=>{await supabase().auth.signOut();nav('/login')}}>Sign out</button></div></Fallback>}
function Fallback({children}:{children:React.ReactNode}){return <div style={{minHeight:'100vh',display:'grid',placeItems:'center',padding:24,fontFamily:'Inter,system-ui,sans-serif',background:'#07070a',color:'#f8fafc'}}>{children}</div>}
const card:React.CSSProperties={width:360,padding:24,border:'1px solid #27272f',borderRadius:14,background:'#101016'};const input:React.CSSProperties={display:'block',width:'100%',boxSizing:'border-box',margin:'10px 0',padding:11,border:'1px solid #333',borderRadius:7,background:'#181822',color:'white'};const button:React.CSSProperties={padding:'10px 14px',border:0,borderRadius:7,background:'#7c3aed',color:'white',fontWeight:700,cursor:'pointer'};const pill:React.CSSProperties={padding:'7px 10px',border:'1px solid #333',borderRadius:999}
