import React from 'react'
import { LAYOUT_SCHEMA_VERSION, RUNTIME_VERSION, type EditorDocument, type EditorPage, type RuntimeManifest, type StudioNode, type ValidationResult } from '@platform/contracts'
import { canMoveNode, canNodeContainChildren, findNodeById, resolveNodeDropTarget, walkStudioNodes, type EditorTool, type NodeDropPosition, type useEditorState } from '@platform/builder-core'
import { RuntimeRenderer, RuntimeSitePreview, type RuntimeNodeEditorProps } from '@platform/runtime-renderer'
import { AppThemeSelector } from '@platform/ui'
import { ActionFeedback, useStudioFeedback, validationIssueMessages } from './ActionFeedback'
import { CanvasChromeOverlay } from './CanvasChromeOverlay'
import { canvasDropPosition } from './canvas-drag'
import { canvasNodeIdFromTarget } from './canvas-selection'
import { ELEMENTS, VIEWPORTS } from './elements'
import { Inspector } from './Inspector'
import { apiFetch } from './api'
import { backToLayoutsRequiresConfirmation, DEFAULT_PANEL_VISIBILITY, StudioActionGate, toggleStudioPanel, toolbarModeForWidth, type StudioAction } from './studio-chrome'

type DropPosition=NodeDropPosition|null
type StudioEditorController=ReturnType<typeof useEditorState>
const btn:React.CSSProperties={border:'1px solid var(--border)',background:'var(--surface)',color:'var(--text)',borderRadius:6,padding:'7px 10px',fontSize:12,cursor:'pointer'}
const primary:React.CSSProperties={...btn,background:'var(--primary)',borderColor:'var(--primary)',color:'var(--primary-text)',fontWeight:700}
const iconBtn:React.CSSProperties={...btn,minWidth:34,padding:'7px 8px'}
const samples={projects:[{id:'p1',slug:'visualbuild',title:'VisualBuild',short_description:'Visual development tooling.',technologies:['React','TypeScript'],featured:true,published:true,display_order:1},{id:'p2',slug:'documents',title:'Document Platform',short_description:'Secure document management.',technologies:['React','Node.js'],featured:true,published:true,display_order:2}],notes:[{id:'n1',slug:'runtime-renderers',title:'Runtime Renderers',summary:'Keeping editor and production rendering aligned.',published:true,display_order:1}],experience:[{id:'e1',company:'SpearHub',role:'Web Developer',summary:'Built ERP and product experiences.',published:true,display_order:1}],apps:[{id:'a1',slug:'job-matcher',name:'Global Job Matcher',short_description:'Resume-aware job matching.',status:'coming_soon',published:true,display_order:1}]}

export function StudioEditor({editor,layouts,onBackToLayouts,onOpenLayout,onOpenDocument,onCreateLayout,onDuplicateLayout,onArchiveLayout,onRefreshLayouts}:{editor:StudioEditorController;layouts:any[];onBackToLayouts:()=>void;onOpenLayout:(id:string)=>void;onOpenDocument:(document:EditorDocument)=>void;onCreateLayout:(template:'blank'|'cosmic')=>void;onDuplicateLayout:(id:string)=>void;onArchiveLayout:(id:string)=>void;onRefreshLayouts:()=>Promise<void>}){
  const {state,currentPage}=editor
  const [leftTab,setLeftTab]=React.useState<'elements'|'layers'>('elements')
  const [panels,setPanels]=React.useState(DEFAULT_PANEL_VISIBILITY)
  const [search,setSearch]=React.useState(''),[dragTool,setDragTool]=React.useState<EditorTool|null>(null),[dragId,setDragId]=React.useState<string|null>(null),[dragOver,setDragOver]=React.useState<string|null>(null),[dropPosition,setDropPosition]=React.useState<DropPosition>(null)
  const dragToolRef=React.useRef<EditorTool|null>(null),dragIdRef=React.useRef<string|null>(null)
  const canvasSurfaceRef=React.useRef<HTMLDivElement>(null),canvasContentRef=React.useRef<HTMLDivElement>(null)
  const toolbarRef=React.useRef<HTMLDivElement>(null),actionGateRef=React.useRef(new StudioActionGate())
  const [toolbarWidth,setToolbarWidth]=React.useState(()=>typeof window==='undefined'?1500:window.innerWidth)
  const [pending,setPending]=React.useState<Record<StudioAction,boolean>>({save:false,validate:false,publish:false})
  const [draftBusy,setDraftBusy]=React.useState(false),[preview,setPreview]=React.useState(false),[previewRoute,setPreviewRoute]=React.useState(0),[layoutMenu,setLayoutMenu]=React.useState(false),[overflowMenu,setOverflowMenu]=React.useState(false),[leavePrompt,setLeavePrompt]=React.useState(false),[pageName,setPageName]=React.useState('New Page')
  const {feedback,show:showFeedback,dismiss:dismissFeedback}=useStudioFeedback()
  const selected=state.selectedNodeId?findNodeById(state.schema.root,state.selectedNodeId):null
  const readonly=state.versionStatus==='published'
  const showLeft=panels.left,showRight=panels.right
  const toolbarMode=toolbarModeForWidth(toolbarWidth)
  const requestBackToLayouts=()=>{if(backToLayoutsRequiresConfirmation(state.dirty))setLeavePrompt(true);else onBackToLayouts()}

  React.useLayoutEffect(()=>{const toolbar=toolbarRef.current;if(!toolbar)return;const update=()=>setToolbarWidth(toolbar.getBoundingClientRect().width);update();window.addEventListener('resize',update);const observer=typeof ResizeObserver==='undefined'?null:new ResizeObserver(update);observer?.observe(toolbar);return()=>{window.removeEventListener('resize',update);observer?.disconnect()}},[])

  const beginAction=React.useCallback((action:StudioAction)=>{if(!actionGateRef.current.begin(action))return false;setPending(current=>({...current,[action]:true}));return true},[])
  const endAction=React.useCallback((action:StudioAction)=>{actionGateRef.current.end(action);setPending(current=>({...current,[action]:false}))},[])

  const persistDocument=React.useCallback(async()=>{
    if(!state.versionId)throw new Error('Missing layout version')
    const doc=editor.exportDocument() as EditorDocument
    const response=await apiFetch<any>(`/api/studio/versions/${state.versionId}/document`,{method:'PUT',body:JSON.stringify({document:doc})})
    editor.loadDocument(response.data,state.pageId)
    editor.markSaved()
    await onRefreshLayouts()
    return response
  },[editor,onRefreshLayouts,state.pageId,state.versionId])

  const save=React.useCallback(async()=>{
    if(readonly||!state.versionId||actionGateRef.current.isPending('publish')||!beginAction('save'))return false
    try{await persistDocument();showFeedback({tone:'success',title:'Layout saved successfully'});return true}catch(error:unknown){showFeedback({tone:'error',title:'Layout could not be saved. Review the document and try again.',details:validationDetailsFromError(error)});return false}finally{endAction('save')}
  },[beginAction,endAction,persistDocument,readonly,showFeedback,state.versionId])
  const validate=async()=>{if(!state.versionId||!beginAction('validate'))return;try{const response=await apiFetch<any>(`/api/studio/versions/${state.versionId}/validate`,{method:'POST'});const result=response.data?.validation as ValidationResult|undefined;if(result?.valid)showFeedback({tone:'success',title:'Layout is valid and ready to publish',details:result.warnings.map(issue=>issue.message)});else showFeedback({tone:'error',title:'Layout has validation errors',details:result?.issues.map(issue=>issue.message)||[]})}catch(error:unknown){showFeedback({tone:'error',title:'Layout has validation errors',details:validationDetailsFromError(error)})}finally{endAction('validate')}}
  const publish=async()=>{if(readonly||!state.versionId||actionGateRef.current.isPending('save')||!beginAction('publish'))return;try{await persistDocument();const response=await apiFetch<any>(`/api/studio/versions/${state.versionId}/publish`,{method:'POST',body:JSON.stringify({changelog:'Published from Studio',thumbnail_data:createThumbnailData(editor.exportDocument())})});editor.loadDocument(response.data.document,state.pageId);await onRefreshLayouts();showFeedback({tone:'success',title:'Layout version published successfully'})}catch(error:unknown){showFeedback({tone:'error',title:'Layout version could not be published.',details:validationDetailsFromError(error)})}finally{endAction('publish')}}
  const createDraft=async()=>{if(draftBusy)return;setDraftBusy(true);try{const response=await apiFetch<any>(`/api/studio/layouts/${state.layoutId}/drafts`,{method:'POST'});onOpenDocument(response.data);showFeedback({tone:'success',title:`Draft v${response.data.versionNumber} created`});await onRefreshLayouts()}catch{showFeedback({tone:'error',title:'A new draft could not be created.'})}finally{setDraftBusy(false)}}

  React.useEffect(()=>{const onKey=(e:KeyboardEvent)=>{const input=['INPUT','TEXTAREA','SELECT'].includes((document.activeElement?.tagName||''));if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='s'){e.preventDefault();save()}else if(!readonly&&(e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='z'){e.preventDefault();e.shiftKey?editor.redo():editor.undo()}else if(!readonly&&(e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='d'){e.preventDefault();editor.duplicateSelected()}else if(!readonly&&(e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='c'&&!input){e.preventDefault();editor.copySelected()}else if(!readonly&&(e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='v'&&!input){e.preventDefault();editor.pasteClipboard()}else if(!readonly&&!input&&(e.key==='Delete'||e.key==='Backspace')){e.preventDefault();editor.deleteSelected()}};window.addEventListener('keydown',onKey);return()=>window.removeEventListener('keydown',onKey)},[editor,readonly,save])

  const canInsertAt=(parentId:string|null)=>{if(parentId===null)return true;const parent=findNodeById(state.schema.root,parentId);return Boolean(parent&&canNodeContainChildren(parent)&&!parent.meta?.locked)}
  const toolStart=(e:React.DragEvent,tool:EditorTool)=>{if(readonly)return;dragToolRef.current=tool;dragIdRef.current=null;setDragTool(tool);setDragId(null);e.dataTransfer.setData('application/x-tool',tool);e.dataTransfer.effectAllowed='copy'}
  const nodeStart=(e:React.DragEvent,id:string)=>{const node=findNodeById(state.schema.root,id);if(readonly||!node||node.meta?.locked)return;dragIdRef.current=id;dragToolRef.current=null;setDragId(id);setDragTool(null);editor.selectNode(id);e.dataTransfer.setData('application/x-node',id);e.dataTransfer.effectAllowed='move'}
  const overNode=(e:React.DragEvent,id:string)=>{if(readonly)return;e.stopPropagation();const target=findNodeById(state.schema.root,id);if(!target)return;const rect=(e.currentTarget as HTMLElement).getBoundingClientRect();const position=canvasDropPosition(e.clientY-rect.top,rect.height,canNodeContainChildren(target)&&!target.meta?.locked);const destination=resolveNodeDropTarget(state.schema.root,id,position);const nodeId=dragIdRef.current||dragId;const tool=dragToolRef.current||dragTool;const valid=Boolean(destination&&(nodeId?canMoveNode(state.schema.root,nodeId,destination.parentId,destination.index):tool&&canInsertAt(destination.parentId)));if(!valid){setDragOver(null);setDropPosition(null);return}e.preventDefault();e.dataTransfer.dropEffect=nodeId?'move':'copy';setDragOver(id);setDropPosition(position)}
  const dropNode=(e:React.DragEvent,targetId:string)=>{if(readonly||!dropPosition)return;e.preventDefault();e.stopPropagation();const destination=resolveNodeDropTarget(state.schema.root,targetId,dropPosition);const nodeId=dragIdRef.current||e.dataTransfer.getData('application/x-node');const tool=(dragToolRef.current||e.dataTransfer.getData('application/x-tool')) as EditorTool;if(destination&&nodeId&&canMoveNode(state.schema.root,nodeId,destination.parentId,destination.index))editor.moveNode(nodeId,destination.parentId,destination.index);else if(destination&&tool&&canInsertAt(destination.parentId))editor.addNode(tool,destination.parentId,destination.index);clearDrag()}
  const rootDrop=(e:React.DragEvent)=>{if(readonly)return;e.preventDefault();const nodeId=dragIdRef.current||e.dataTransfer.getData('application/x-node');const tool=(dragToolRef.current||e.dataTransfer.getData('application/x-tool')) as EditorTool;if(nodeId&&canMoveNode(state.schema.root,nodeId,null,state.schema.root.length))editor.moveNode(nodeId,null,state.schema.root.length);else if(tool)editor.addNode(tool,null);clearDrag()}
  const clearDrag=()=>{dragToolRef.current=null;dragIdRef.current=null;setDragTool(null);setDragId(null);setDragOver(null);setDropPosition(null)}
  const selectCanvasNode=(event:React.MouseEvent<HTMLElement>)=>{event.stopPropagation();editor.selectNode(canvasNodeIdFromTarget(event.target))}

  const doc=editor.exportDocument() as EditorDocument
  const sampleContent=React.useMemo(()=>{const out:Record<string,unknown>={};doc.pages.forEach(page=>walkStudioNodes(page.schema.root,node=>{Object.values(node.bindings||{}).forEach((binding:any)=>{if(binding.type==='content')out[binding.key]=binding.sample??binding.fallback??binding.label??binding.key;if(binding.type==='setting')out[binding.key]=binding.sample??binding.fallback??binding.label??binding.key})}));return out},[state.pages,state.versionId])
  const manifest:RuntimeManifest=React.useMemo(()=>{const header=doc.pages.find(p=>p.pageType==='system'&&p.slug==='_header'),footer=doc.pages.find(p=>p.pageType==='system'&&p.slug==='_footer');return{releaseId:null,layoutVersionId:doc.versionId,schemaVersion:LAYOUT_SCHEMA_VERSION,runtimeMinVersion:RUNTIME_VERSION,designTokens:doc.designTokens,routes:doc.pages.filter(p=>p.pageType!=='system').sort((a,b)=>a.sortOrder-b.sortOrder).map(p=>({path:p.routePattern,pageId:p.id,slug:p.slug,name:p.name,pageType:p.pageType,collectionName:p.schema.collectionName,seo:p.seoDefaults,schema:p.schema})),globals:{header:header?.schema,footer:footer?.schema},content:sampleContent,settings:sampleContent,media:{},collections:samples,generatedAt:new Date().toISOString()}},[doc,sampleContent])
  const currentRoute=manifest.routes[Math.min(previewRoute,Math.max(0,manifest.routes.length-1))]
  const filtered=ELEMENTS.filter(e=>e.label.toLowerCase().includes(search.toLowerCase()))
  const viewport=VIEWPORTS[state.mode]
  const editorNodeProps=(node:StudioNode):RuntimeNodeEditorProps=>{
    const nodeStyle:React.CSSProperties={}
    if(node.meta?.locked)nodeStyle.opacity=.82
    return {
      style:nodeStyle,draggable:!readonly&&!node.meta?.locked,
      onDragStart:(e:any)=>{e.stopPropagation();if(!readonly&&!node.meta?.locked)nodeStart(e,node.id)},
      onDragOver:(e:any)=>{if(readonly)return;overNode(e,node.id)},
      onDrop:(e:any)=>{if(readonly)return;e.preventDefault();e.stopPropagation();dropNode(e,node.id)},
      onDragEnd:clearDrag,
    }
  }

  React.useEffect(()=>{if(toolbarMode==='wide')setOverflowMenu(false)},[toolbarMode])
  const runSecondary=(action:()=>void)=>{setOverflowMenu(false);action()}
  const secondaryTools=(stacked=false)=><div data-studio-toolbar-secondary style={{display:'flex',alignItems:'center',justifyContent:stacked?'flex-start':'flex-end',flexWrap:'wrap',gap:6}}>
    <button style={btn} title="Duplicate current layout" onClick={()=>runSecondary(()=>{if(state.layoutId)onDuplicateLayout(state.layoutId)})}>Duplicate Layout</button>
    <button style={{...btn,color:'var(--danger)'}} title="Archive current layout" onClick={()=>runSecondary(()=>{if(state.layoutId)onArchiveLayout(state.layoutId)})}>Archive</button>
    {!readonly&&<><button style={btn} onClick={()=>runSecondary(()=>{const name=prompt('Page name',pageName)||'';if(name.trim())editor.addPage(name.trim())})}>Add Page</button><button style={iconBtn} title="Move page earlier" onClick={()=>runSecondary(()=>editor.reorderPage(state.pageId,-1))}>Page ↑</button><button style={iconBtn} title="Move page later" onClick={()=>runSecondary(()=>editor.reorderPage(state.pageId,1))}>Page ↓</button><button style={iconBtn} title="Duplicate page" onClick={()=>runSecondary(()=>editor.duplicatePage(state.pageId))}>Duplicate Page</button>{currentPage&&currentPage.pageType!=='system'&&<button style={iconBtn} title="Delete page" onClick={()=>runSecondary(()=>{if(confirm(`Delete ${currentPage.name}?`))editor.deletePage(state.pageId)})}>Delete Page</button>}</>}
    <button style={iconBtn} aria-label="Zoom out" onClick={()=>runSecondary(()=>editor.setZoom(state.zoom-.1))}>−</button><span style={{fontSize:11,color:'var(--text-muted)',minWidth:38,textAlign:'center'}}>{Math.round(state.zoom*100)}%</span><button style={iconBtn} aria-label="Zoom in" onClick={()=>runSecondary(()=>editor.setZoom(state.zoom+.1))}>+</button>
    {!readonly&&<><button style={iconBtn} onClick={()=>runSecondary(editor.undo)}>Undo</button><button style={iconBtn} onClick={()=>runSecondary(editor.redo)}>Redo</button></>}
    <button style={btn} onClick={()=>runSecondary(()=>setPreview(true))}>Preview</button><AppThemeSelector align={stacked?'left':'right'}/>
  </div>

  return <>
    <div ref={toolbarRef} data-studio-toolbar-mode={toolbarMode} style={{minHeight:52,flexShrink:0,display:'flex',flexWrap:'wrap',alignItems:'center',gap:8,padding:'7px 12px',borderBottom:'1px solid var(--border)',background:'var(--surface)',color:'var(--text)',zIndex:30,overflow:'visible'}}>
      <div data-studio-toolbar-primary style={{display:'flex',alignItems:'center',flexWrap:'wrap',gap:7,flex:'1 1 760px',minWidth:0}}>
        <button style={btn} aria-label="Back to Layouts" title="Back to Layouts" onClick={requestBackToLayouts}>{toolbarMode==='narrow'?'←':'← Layouts'}</button>
        <div style={{position:'relative'}}><button style={{...btn,minWidth:toolbarMode==='narrow'?130:170,maxWidth:220,textAlign:'left',overflow:'hidden',textOverflow:'ellipsis',whiteSpace:'nowrap'}} onClick={()=>setLayoutMenu(value=>!value)}>{state.layoutName} · v{state.versionNumber} {readonly?'✓':''}</button>{layoutMenu&&<div style={{position:'absolute',top:38,left:0,width:280,maxHeight:420,overflow:'auto',background:'var(--surface)',border:'1px solid var(--border)',borderRadius:8,zIndex:100,boxShadow:'0 16px 40px var(--shadow)',padding:6}}><button style={{...btn,width:'100%',marginBottom:5}} onClick={()=>onCreateLayout('cosmic')}>+ Cosmic starter</button><button style={{...btn,width:'100%',marginBottom:7}} onClick={()=>onCreateLayout('blank')}>+ Blank layout</button>{layouts.map(layout=><button key={layout.id} style={{...btn,width:'100%',textAlign:'left',marginTop:4}} onClick={()=>{setLayoutMenu(false);onOpenLayout(layout.id)}}>{layout.name}</button>)}</div>}</div>
        <select aria-label="Current page" value={state.pageId} onChange={event=>editor.switchPage(event.target.value)} style={{...btn,minWidth:toolbarMode==='narrow'?120:145,maxWidth:180}}>{state.pages.slice().sort((a:EditorPage,b:EditorPage)=>a.sortOrder-b.sortOrder).map((page:EditorPage)=><option key={page.id} value={page.id}>{page.name}{page.pageType==='system'?' · Global':''}</option>)}</select>
        <div aria-label="Canvas responsive mode" style={{display:'flex',gap:4}}>{(['desktop','tablet','mobile'] as const).map(mode=><button key={mode} aria-label={VIEWPORTS[mode].label} title={VIEWPORTS[mode].label} style={{...btn,padding:toolbarMode==='narrow'?'7px 8px':'7px 10px',background:state.mode===mode?'var(--primary)':'var(--surface)',color:state.mode===mode?'var(--primary-text)':'var(--text)'}} onClick={()=>editor.setMode(mode)}>{toolbarMode==='narrow'?VIEWPORTS[mode].label[0]:VIEWPORTS[mode].label}</button>)}</div>
        {!readonly&&<><button disabled={pending.save||pending.publish} aria-busy={pending.save} style={primary} onClick={save}>{pending.save?'Saving...':state.dirty?'Save*':'Save'}</button><button disabled={pending.validate} aria-busy={pending.validate} style={btn} onClick={validate}>{pending.validate?'Validating...':'Validate'}</button><button disabled={pending.publish||pending.save} aria-busy={pending.publish} style={btn} onClick={publish}>{pending.publish?'Publishing...':'Publish'}</button></>}
        {readonly&&<button disabled={draftBusy} style={primary} onClick={createDraft}>{draftBusy?'Creating Draft...':'Create Draft'}</button>}
      </div>
      {toolbarMode==='wide'?secondaryTools(false):<div style={{position:'relative',marginLeft:'auto'}}><button type="button" aria-haspopup="menu" aria-expanded={overflowMenu} style={btn} onClick={()=>setOverflowMenu(value=>!value)}>More ▾</button>{overflowMenu&&<div role="menu" data-studio-toolbar-overflow style={{position:'absolute',top:38,right:0,zIndex:200,width:330,maxWidth:'calc(100vw - 24px)',padding:10,border:'1px solid var(--border)',borderRadius:8,background:'var(--surface)',boxShadow:'0 16px 40px var(--shadow)'}}>{secondaryTools(true)}</div>}</div>}
    </div>
    <ActionFeedback feedback={feedback} onDismiss={dismissFeedback}/>
    <div data-studio-workspace style={{display:'flex',flex:1,minHeight:0,position:'relative'}}>
      {showLeft&&<aside data-studio-panel="left" style={{width:292,flexShrink:0,borderRight:'1px solid var(--border)',background:'var(--surface)',display:'flex',flexDirection:'column',color:'var(--text)'}}><div style={{display:'grid',gridTemplateColumns:'1fr 1fr'}}><button style={{...btn,borderRadius:0,border:'none',borderBottom:leftTab==='elements'?'2px solid var(--primary)':'1px solid var(--border)'}} onClick={()=>setLeftTab('elements')}>Elements</button><button style={{...btn,borderRadius:0,border:'none',borderBottom:leftTab==='layers'?'2px solid var(--primary)':'1px solid var(--border)'}} onClick={()=>setLeftTab('layers')}>Layers</button></div>{leftTab==='elements'?<><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search elements…" style={{margin:10,padding:'8px 9px',border:'1px solid var(--border)',borderRadius:6,background:'var(--surface-alt)',color:'var(--text)'}}/><div style={{overflow:'auto',display:'grid',gridTemplateColumns:'repeat(3,1fr)',gap:7,padding:'0 9px 12px'}}>{filtered.map(el=><div key={el.tool} draggable={!readonly} onDragStart={e=>toolStart(e,el.tool)} onDragEnd={clearDrag} onDoubleClick={()=>!readonly&&editor.addNode(el.tool,null)} style={{border:'1px solid var(--border)',borderRadius:7,minHeight:62,display:'grid',placeItems:'center',textAlign:'center',cursor:readonly?'not-allowed':'grab',background:'var(--surface-alt)',fontSize:10}}><div><div style={{fontSize:17,marginBottom:5}}>{el.icon}</div>{el.label}</div></div>)}</div></>:<div style={{overflow:'auto',padding:8}}>{state.schema.root.length?state.schema.root.map((n:StudioNode)=><Layer key={n.id} node={n} depth={0} selected={state.selectedNodeId} onSelect={editor.selectNode} onDelete={readonly?undefined:editor.deleteNode}/>):<p style={{color:'var(--text-muted)',fontSize:12}}>Empty page</p>}</div>}</aside>}
      <main data-studio-canvas style={{flex:1,minWidth:0,overflow:'auto',background:'var(--bg)',padding:24}} onDragOver={e=>{if(!readonly)e.preventDefault()}} onDrop={rootDrop} onClick={()=>editor.selectNode(null)}><div ref={canvasSurfaceRef} onClick={selectCanvasNode} style={{width:viewport.width,maxWidth:'100%',margin:'0 auto',transformOrigin:'top center',transform:`scale(${state.zoom})`,minHeight:480,boxShadow:'0 12px 45px var(--shadow)',transition:'width .2s ease',position:'relative',isolation:'isolate',overflow:'visible'}}><div ref={canvasContentRef} style={{position:'relative',zIndex:0}}>{state.schema.root.length?<RuntimeRenderer schema={state.schema} designTokens={state.designTokens} mode={state.mode} content={sampleContent} settings={sampleContent} collections={samples} media={{}} linkMode="disabled" nodeEditorProps={editorNodeProps}/>:<div style={{minHeight:480,display:'grid',placeItems:'center',border:'1px dashed var(--border)',color:'var(--text-muted)'}}>Drag elements here</div>}</div><CanvasChromeOverlay surfaceRef={canvasSurfaceRef} contentRef={canvasContentRef} selectedNodeId={state.selectedNodeId} dropTargetId={dragOver} dropPosition={dropPosition} mode={state.mode} zoom={state.zoom} geometryVersion={state.schema}/></div></main>
      {showRight&&currentPage&&<aside data-studio-panel="inspector" style={{width:330,flexShrink:0,borderLeft:'1px solid var(--border)',minHeight:0,color:'var(--text)'}}><Inspector node={selected} mode={state.mode} page={currentPage} onUpdateNode={fn=>selected&&editor.updateNode(selected.id,fn)} onUpdatePage={patch=>editor.updatePage(state.pageId,patch)} onUpdateTokens={variables=>editor.setDocumentMeta({designTokens:{...state.designTokens,variables}})} designTokens={state.designTokens.variables}/></aside>}
      <PanelEdgeToggle side="left" open={showLeft} onToggle={()=>setPanels(current=>toggleStudioPanel(current,'left'))}/><PanelEdgeToggle side="right" open={showRight} onToggle={()=>setPanels(current=>toggleStudioPanel(current,'right'))}/>
    </div>
    {leavePrompt&&<div role="dialog" aria-modal="true" aria-labelledby="leave-studio-title" style={{position:'fixed',inset:0,zIndex:60000,display:'grid',placeItems:'center',background:'rgba(0,0,0,.52)',padding:20}}><div style={{width:'min(430px,100%)',padding:22,border:'1px solid var(--border)',borderRadius:12,background:'var(--surface)',color:'var(--text)',boxShadow:'0 18px 50px var(--shadow)'}}><h2 id="leave-studio-title" style={{margin:'0 0 8px',fontSize:18}}>You have unsaved changes. Leave without saving?</h2><p style={{margin:'0 0 18px',color:'var(--text-muted)',fontSize:13}}>Your persisted layout will remain unchanged.</p><div style={{display:'flex',justifyContent:'flex-end',gap:8}}><button style={btn} onClick={()=>setLeavePrompt(false)}>Stay</button><button style={{...btn,color:'var(--danger)'}} onClick={()=>{setLeavePrompt(false);onBackToLayouts()}}>Leave without saving</button></div></div></div>}
    {preview&&currentRoute&&<div style={{position:'fixed',inset:0,zIndex:10000,background:'var(--bg)',display:'flex',flexDirection:'column'}}><div style={{height:48,padding:'0 12px',display:'flex',alignItems:'center',gap:8,borderBottom:'1px solid var(--border)',background:'var(--surface)',color:'var(--text)'}}><strong style={{marginRight:8}}>Runtime Preview</strong>{manifest.routes.map((r,i)=><button key={r.pageId} style={{...btn,background:i===previewRoute?'var(--primary)':'var(--surface)',color:i===previewRoute?'var(--primary-text)':'var(--text)'}} onClick={()=>setPreviewRoute(i)}>{r.name}</button>)}<div style={{flex:1}}/><span style={{fontSize:11,color:'var(--text-muted)'}}>same runtime renderer used by Admin/Web</span><button style={primary} onClick={()=>setPreview(false)}>Close</button></div><div style={{flex:1,overflow:'auto'}}><RuntimeSitePreview manifest={manifest} route={currentRoute} mode={state.mode} onNavigate={href=>{const i=previewRouteIndex(manifest,href);if(i>=0)setPreviewRoute(i)}}/></div></div>}
  </>
}

function Layer({node,depth,selected,onSelect,onDelete}:{node:StudioNode;depth:number;selected:string|null;onSelect:(id:string)=>void;onDelete?:((id:string)=>void)}){
 return <div><div onClick={()=>onSelect(node.id)} style={{display:'flex',alignItems:'center',gap:6,padding:'6px 5px 6px '+(6+depth*14)+'px',borderRadius:5,background:selected===node.id?'color-mix(in srgb,var(--primary) 20%,transparent)':'transparent',fontSize:11,cursor:'pointer'}}><span style={{color:'var(--text-muted)'}}>{node.children?.length?'▾':'·'}</span><span style={{flex:1,overflow:'hidden',whiteSpace:'nowrap',textOverflow:'ellipsis'}}>{node.meta?.label||node.meta?.sectionLabel||node.type}</span>{node.meta?.locked&&<span>🔒</span>}{onDelete&&<button style={{border:0,background:'transparent',color:'var(--text-muted)',cursor:'pointer'}} onClick={e=>{e.stopPropagation();onDelete(node.id)}}>×</button>}</div>{node.children?.map(c=><Layer key={c.id} node={c} depth={depth+1} selected={selected} onSelect={onSelect} onDelete={onDelete}/>)}</div>
}

function PanelEdgeToggle({side,open,onToggle}:{side:'left'|'right';open:boolean;onToggle:()=>void}){
  const left=side==='left';const label=left?(open?'Collapse left panel':'Expand left panel'):(open?'Collapse inspector':'Expand inspector');const icon=left?(open?'‹':'›'):(open?'›':'‹')
  return <button type="button" data-studio-edge-toggle={side} aria-label={label} title={label} onClick={onToggle} style={{position:'absolute',top:'50%',left:left?(open?292:6):undefined,right:left?undefined:(open?330:6),transform:`translate(${open?(left?'-50%':'50%'):'0'},-50%)`,zIndex:120,width:32,height:56,padding:0,border:'1px solid var(--border)',borderRadius:left?'0 8px 8px 0':'8px 0 0 8px',background:'var(--surface)',color:'var(--text)',boxShadow:'0 8px 24px var(--shadow)',fontSize:24,lineHeight:1,cursor:'pointer'}}>{icon}</button>
}

function createThumbnailData(doc:EditorDocument){const bg=doc.designTokens.variables['--site-bg']||'#07070a',text=doc.designTokens.variables['--site-text']||'#f8fafc',accent=doc.designTokens.variables['--site-accent']||'#22d3ee';const title=doc.layoutName.replace(/[&<>"']/g,'');const svg=`<svg xmlns="http://www.w3.org/2000/svg" width="1200" height="675"><rect width="1200" height="675" fill="${bg}"/><circle cx="930" cy="170" r="220" fill="${accent}" opacity=".12"/><text x="70" y="280" font-family="system-ui" font-size="34" fill="${accent}">PUBLISHED LAYOUT</text><text x="70" y="360" font-family="system-ui" font-size="72" font-weight="700" fill="${text}">${title}</text><text x="70" y="420" font-family="system-ui" font-size="25" fill="${text}" opacity=".65">${doc.pages.filter(p=>p.pageType!=='system').length} pages · v${doc.versionNumber}</text></svg>`;return `data:image/svg+xml;charset=UTF-8,${encodeURIComponent(svg)}`}

function previewRouteIndex(manifest:RuntimeManifest,href:string){const clean=href.split('#')[0].split('?')[0]||'/';for(let i=0;i<manifest.routes.length;i++){const pattern=manifest.routes[i].path.replace(/:[A-Za-z0-9_]+/g,'[^/]+');if(new RegExp(`^${pattern}/?$`).test(clean))return i}return -1}

function validationDetailsFromError(error:unknown){const record=error&&typeof error==='object'?error as Record<string,unknown>:null;return validationIssueMessages(record?.payload||error)}
